const {webkit,chromium}=require('playwright');
exports.webkit=webkit;exports.chromium=chromium;
exports.open=async function(opts){opts=opts||{};
 const b=await (opts.eng||webkit).launch();
 const ctx=await b.newContext({viewport:opts.vp||{width:420,height:912},deviceScaleFactor:2,hasTouch:!!opts.touch});
 const p=await ctx.newPage();p.errs=[];
 p.on('pageerror',e=>p.errs.push('PE '+e.message));
 p.on('console',m=>{if(m.type()==='error')p.errs.push('CE '+m.text().slice(0,300));});
 await p.addInitScript((s)=>{try{if(!localStorage.getItem('qlv_settings'))localStorage.setItem('qlv_settings',JSON.stringify(s));}catch(e){}},Object.assign({},opts.settings||{typer:false}));
 await p.goto('file://'+(process.env.QF_FILE||'/workspace/qinlove/index.html'));await p.waitForTimeout(400);
 p.browser_=b;return p;};
const L=exports;
exports.btns=p=>p.$$eval('#choices .cbtn',els=>els.map(e=>e.textContent));
exports.txt=p=>p.$eval('#txt',e=>e.textContent);
exports.click=async function(p,re,quiet){const list=await L.btns(p);const i=list.findIndex(t=>re.test(t));if(i<0)throw new Error('no btn '+re+' in ['+list.join(' | ')+']');await p.locator('#choices .cbtn').nth(i).click();await p.waitForTimeout(50);return list[i];};
exports.tryClick=async function(p,re){try{return await L.click(p,re);}catch(e){return null;}};
exports.flush=async function(p){for(let i=0;i<60;i++){if(await p.$eval('#map',e=>e.className.indexOf('on')>=0))return 'map';const n=await p.$$eval('#choices .cbtn',e=>e.length);const busy=await p.$eval('#busy',e=>e.className==='on');if(n&&!busy)return true;const med=await p.$eval('#med',e=>e.className.indexOf('on')>=0);if(med)return 'med';const map=await p.$eval('#map',e=>e.className.indexOf('on')>=0);if(map)return 'map';const cg=await p.$eval('#cgv',e=>e.className==='on');if(cg){await p.click('#cgv');await p.waitForTimeout(60);continue;}if(!busy)await p.evaluate(()=>UI.adv());await p.waitForTimeout(busy?150:25);}return false;};
exports.pick=async function(p,re){await L.flush(p);return L.click(p,re);};
exports.toMap=async function(p){for(let i=0;i<30;i++){const r=await L.flush(p);if(r==='map')return true;if(r==='med'){await L.medSolve(p,true);continue;}const l=await L.btns(p);let k=l.findIndex(t=>/返回地圖|🗺|繼續|收進回憶|開始|告辭|返回/.test(t));if(k<0)k=0;await p.locator('#choices .cbtn').nth(k).click();await p.waitForTimeout(40);}return false;};
exports.medSolve=async function(p,right){for(const i of [0,1,2,3]){await p.click('[data-four="'+i+'"]');await p.waitForTimeout(20);}
 const ans=await p.evaluate(()=>({dx:Med.cur.d.dx,rx:Med.cur.d.rx,w:Med.cur.d.wrong[0],rw:Med.cur.d.rxw[0]}));
 await p.locator('[data-dx]').filter({hasText:right?ans.dx:ans.w}).first().click();await p.waitForTimeout(20);
 await p.locator('[data-rx]').filter({hasText:right?ans.rx:ans.rw}).first().click();await p.waitForTimeout(20);await p.click('#mdDone');await p.waitForTimeout(60);};
exports.newGame=async function(p,name){await p.click('#tNew');await p.waitForTimeout(80);if(name)await p.fill('#nmIn',name);await p.locator('#dlA .btn.pri').click();await p.waitForTimeout(100);};
exports.shot=async(p,n)=>{await p.waitForTimeout(650);return p.screenshot({path:'/workspace/qinlove/screenshots/'+n+'.png'});};
exports.state=(p,expr)=>p.evaluate(expr);
exports.goPl=async function(p,pl){await L.toMap(p);await p.click('.pin[data-pl="'+pl+'"]');await p.waitForTimeout(30);if(await p.$eval('#map',e=>e.className.indexOf('on')>=0))await p.click('.pin[data-pl="'+pl+'"]');await p.waitForTimeout(60);return L.flush(p);};
exports.setPer=(p,per)=>p.evaluate(n=>{S.per=n;},per);
exports.talk=async function(p,id){const nm=await p.evaluate(i=>CHARS[i].n,id);const l=await L.btns(p);const k=l.findIndex(t=>t.indexOf(nm)>=0||/👤/.test(t));if(k<0)throw new Error('no talk '+id+' in '+l.join('|'));await p.locator('#choices .cbtn').nth(k).click();await p.waitForTimeout(40);await L.flush(p);};
