/* ===== 離線事件庫、NPC 自主、交談、家族事件、師父、歷史大事、每日鉤子 ===== */
var Ev={};
function evc(id,i){return ch(id[1],'evc',{id:id[0],i:i});}
Ev.LIB=[
 /* ---- 流放路 ---- */
 {id:'rSteal',ctx:['road'],w:3,cd:4,cond:function(){return S.road&&Eng.foodKeys().length;},text:function(){var m=P(S.road.mates[0]);return ['半夜，你聽見窸窣聲——'+m.n+'的手正伸進你家的糧袋。'];},
  opts:[['當場揪住'+'他',function(){var m=P(S.road.mates[0]);var me=pc();if(me.sk.mart+me.at.con*2+rnd(20)>m.at.con*2+20){People.rel(m.id,{aff:-8},'偷糧被'+me.n+'抓住');return '你一把攥住他的手腕。'+m.n+'訕訕地鬆手：「誤會、誤會……」';}var k=Eng.foodKeys()[0];if(k)Inv.add(k,-1);me.hp=clamp(me.hp-5,1,100);return m.n+'一把推開你，抓了一把糧就跑。（糧-1）';}],['裝睡，由他去',function(){var k=Eng.foodKeys()[0];if(k)Inv.add(k,-1);var m=P(S.road.mates[0]);People.rel(m.id,{aff:2});return '你閉上眼。他拿走了一點，第二天看你的眼神有些躲閃。（糧-1）';}],['喊衙役',function(){var g=P(S.road.guards[1]);var m=P(S.road.mates[0]);m.hp=clamp(m.hp-10,1,100);People.rel(m.id,{aff:-15},'被'+pc().n+'告發偷糧');Bond.apply(m.id,{e:{怨恨:12}});return g.n+'提著燈過來，給了'+m.n+'兩鞭子。'+m.n+'看你的眼神陰沉下來。';}]]},
 {id:'rBribe',ctx:['road'],w:3,cd:3,cond:function(){return S.road;},text:function(){var g=P(S.road.guards[0]);return [[g.id,'「這一路上，'+Fam.name()+'吃的喝的，可都是老子照應。懂規矩不？」'],g.n+'把手伸到你面前，搓了搓手指。'];},
  opts:[['塞五錢',function(){if(S.gold<5)return '你翻遍全身，只摸出幾枚銅子。'+P(S.road.guards[0]).n+'啐了一口。';Inv.gold(-5);S.flags['bribed_'+S.road.guards[0]]=S.day;People.rel(S.road.guards[0],{aff:5});addLog('〔行賄〕給押解衙役五錢','行');return '他掂了掂，臉色好看了些：「今兒走慢點也行。」';}],['裝作聽不懂',function(){var g=P(S.road.guards[0]);People.rel(g.id,{aff:-6});Eng.house().forEach(function(p){p.sta=clamp(p.sta-10,0,100);});return '當天下午，'+g.n+'故意把隊伍趕得飛快。（全家體力-10）';}],['求另一位衙役說情',function(){var g2=P(S.road.guards[1]);if(g2.aff>=10||g2.pers.indexOf('憨厚')>=0){People.rel(g2.id,{aff:2});return g2.n+'打了個哈哈：「王哥，算了算了，一家子老小的。」事情就這麼過去了。';}return g2.n+'假裝沒聽見。';}]]},
 {id:'rKind',ctx:['road'],w:2,cd:5,cond:function(){return S.road&&P(S.road.guards[1]).aff>=0;},text:function(){var g=P(S.road.guards[1]);return [g.n+'趁夜色把一塊麥餅塞給你：「給孩子的。別讓王哥看見。」'];},opts:[['道謝收下',function(){Inv.add('cake',1);People.rel(S.road.guards[1],{aff:4,trust:3},pc().n+'收下我給的餅');return '你把餅掰成幾塊，分給家裡最小的。（麥餅+1）';}],['推辭',function(){People.rel(S.road.guards[1],{aff:2,trust:2});return '他愣了愣，撓撓頭走了。';}]]},
 {id:'rStorm',ctx:['road'],w:2,cd:6,cond:function(){return S.road&&(Weather.wet()||S.wx.t<8);},text:function(){return ['夜裡起了風雨，營地四面漏風。家人擠在一起發抖。'];},opts:[['全家擠在一起取暖',function(){Eng.house().forEach(function(p){p.temp=clamp(p.temp+0.4,33,41);p.mood=clamp(p.mood+2,0,100);});return '你們背靠著背，聽著雨聲熬到天亮。';}],['把自己的衣裳給最小的',function(){var y=Eng.house().filter(function(p){return p.id!==S.pc;}).sort(function(a,b){return ageOf(a)-ageOf(b);})[0];if(y){y.temp=clamp(y.temp+0.8,33,41);People.rel(y.id,{aff:6},pc().n+'把衣裳讓給我');}pc().temp-=0.6;if(rand()<0.4)Ill.add(pc(),'cold',1);return (y?y.n:'孩子')+'在你的衣裳裡睡著了。你冷得一夜沒合眼。';}]]},
 {id:'rSickMate',ctx:['road'],w:2,cd:8,cond:function(){return S.road;},text:function(){var m=P(S.road.mates[1]);return [m.n+'發起高燒，渾身滾燙。衙役說：「走不動就扔路邊！」'];},opts:[['替他診治',function(){var m=P(S.road.mates[1]);Ill.add(m,'fever',2);var me=pc();var ok=me.sk.med>=20&&(Inv.has('antipyr')||Inv.has('willow')||rand()<0.4);if(Inv.has('antipyr'))Inv.add('antipyr',-1);if(ok){Ill.cure(m,'fever',5);People.rel(m.id,{aff:12,trust:10},pc().n+'救了我的命');People.rel(S.road.mates[0],{aff:8},pc().n+'救了我家孩子');return '你用冷水擦身、灌下退燒藥。天亮時，'+m.n+'的燒退了。同行的人看你的眼神都不一樣了。';}return '你手邊什麼藥都沒有，只能用濕布替他擦身。他熬過了一夜，但仍很虛弱。';}],['分他一口粥',function(){var k=Eng.foodKeys()[0];if(k)Inv.add(k,-1);People.rel(S.road.mates[1],{aff:6},pc().n+'分我粥');return '他喝了粥，靠著你家的行李睡著了。';}],['不管閒事',function(){People.rel(S.road.mates[1],{aff:-4});return '你別過頭去。';}]]},
 {id:'rBerry',ctx:['road'],w:2,cd:5,cond:function(){return S.road;},text:function(){return ['路邊長著一大片黑亮的漿果，孩子們看得直嚥口水。'];},opts:[['仔細辨認',function(){var it=Forage.ident({});if(it)return '你掐開一顆嘗了嘗——苦，無鳥啄痕。是龍葵生果，有毒。你拉住了孩子們。';Inv.add('fruitP',2);return '看著不像有毒，你摘了兩捧。（野果+2）';}],['不碰',function(){return '你催著孩子們快走。';}]]},
 {id:'rOldFriend',ctx:['road','move'],w:1,cd:30,cond:function(){return S.fam.grudge&&!S.fam.grudge.done&&S.fam.grudge.clues.indexOf('舊識證詞')<0;},text:function(){return ['一個趕車的老漢盯著'+(People.byRel('父')?cn(People.byRel('父')):'你')+'看了半天：「你……你是'+S.fam.sur+'家的？當年那件事，我知道一些內情。」'];},opts:[['細問',function(){var g=S.fam.grudge;g.clues.push('舊識證詞');g.ev++;return '老漢壓低聲音，說出當年告發者收了別人的錢。（翻案線索+1）';}],['怕惹禍，不問',function(){return '老漢嘆了口氣，趕著車走了。';}]]},
 /* ---- 邊地 ---- */
 {id:'fWolf',ctx:['morning'],w:2,cd:10,cond:function(){return S.region==='frontier'&&(S.fam.house||0)<1&&Eng.season()>=2;},text:function(){return ['夜裡有狼摸到你們露宿的地方，叼走了一袋糧。'];},opts:[['加緊搭屋',function(){var k=Eng.foodKeys()[0];if(k)Inv.add(k,-1);return '沒有屋子，就沒有安穩的夜。（糧-1）';}]]},
 {id:'fNeighbor',ctx:['move','morning'],w:2,cd:8,cond:function(){return S.region==='frontier';},text:function(){var n=People.present('village')[0];return ['里中一個土著婦人站在籬笆外打量你們：「新來的流人？」'];},opts:[['客氣問好',function(){var p=genPerson({g:'f',age:40,kind:'npc',job:'farmer',met:1,aff:15,pers:['熱心','開朗'],loc:{r:'frontier',pl:'village'}});p.title='鄰家大娘';Inv.add('seed',2);return p.n+'送了你兩把種子：「這地方，種粟比種麥好。」（種子+2）';}],['不理會',function(){return '婦人撇撇嘴走了。';}]]},
 {id:'fClue',ctx:['move'],w:1,cd:20,cond:function(){return S.region==='frontier'&&S.fam.grudge&&!S.fam.grudge.done&&S.place==='village'&&S.fam.grudge.clues.indexOf('里中舊識')<0;},text:function(){return ['里中一個瞎眼老吏聽說你家的事，摸索著拉住你：「當年那案子，是我抄的文書……」'];},opts:[['扶他坐下細談',function(){var g=S.fam.grudge;g.clues.push('里中舊識');g.ev++;return '老吏說出了當年真正主使者的名字。（翻案線索+1）';}]]},
 {id:'fSick',ctx:['move','morning'],w:2,cd:6,cond:function(){return S.region==='frontier'&&(S.fam.tech.alco||pc().sk.med>=25);},text:function(){return ['里中有人來敲門：「聽說你懂醫？我家當家的從山上摔下來，腿……腿彎了！」'];},opts:[['提著藥箱就走',function(){Med.open({src:'call',ci:Med.caseOf('fracture'),fee:10});return {screen:'med'};}],['今日實在走不開',function(){return '來人失望地走了。';}]]},
 {id:'fMasterHint',ctx:['move','morning'],w:1,cd:15,cond:function(){return S.region==='frontier'&&!S.flags.masterMet;},text:function(){return ['獵戶說，深山雲霧裡住著個怪老頭，「會用刀子剖開人的肚子，再縫回去，人還活著！」'];},opts:[['記在心上',function(){S.flags.masterHint=1;return '你望向雲霧繚繞的山頭。';}]]},
 /* ---- 城中 ---- */
 {id:'cDoor',ctx:['move','morning'],w:2,cd:5,cond:function(){return S.region==='xianyang'&&(S.fam.tech.alco||pc().sk.med>=30);},text:function(){return ['一群人抬著個血淋淋的漢子衝到你面前：「大夫！救救他！」'];},opts:[['立刻動手',function(){Med.open({src:'call',ci:Med.caseOf(pick(['arrow','cut','burn']))});return {screen:'med'};}],['指點他們去找別的醫者',function(){S.fam.fame=Math.max(0,S.fam.fame-1);return '他們罵罵咧咧地走了。';}]]},
 {id:'cThief',ctx:['move'],w:2,cd:8,cond:function(){return S.region==='xianyang'&&S.gold>30;},text:function(){return ['人群裡有隻手輕輕碰了碰你的錢袋。'];},opts:[['反手扣住',function(){if(pc().at.dex+rnd(10)>14)return '你一把扣住那隻手——是個瘦得皮包骨的孩子。你鬆開手，塞給他一個餅。';var n=Math.min(S.gold,10+rnd(20));Inv.gold(-n);return '慢了一步，錢袋輕了'+n+'兩。';}],['捂緊錢袋快步走開',function(){if(rand()<0.6)return '你捂著錢袋擠出人群，回頭只看見一個瘦小的背影鑽進了巷子。';var n=Math.min(S.gold,5+rnd(8));Inv.gold(-n);return '走出老遠才發現，錢袋還是被劃了個口子，少了'+n+'兩。';}]]},
 {id:'cRival',ctx:['move'],w:2,cd:10,cond:function(){return S.region==='xianyang'&&S.fam.fame>=6;},text:function(){return ['一位老醫者在街口高聲說：「剖人肌膚、穿針引線，這是醫術？這是屠戶！」圍觀者越來越多。'];},opts:[['當眾講解消毒之理',function(){var me=pc();if(me.sk.lit+me.sk.med+rnd(30)>80){S.fam.fame+=2;return '你講沸水殺穢、酒精潔創，舉了幾個病例。人群中有人點頭——老醫者拂袖而去。（名聲+2）';}S.fam.notor=(S.fam.notor||0)+2;return '你講得太玄，人們只聽懂了「剖開」二字，紛紛後退。';}],['一笑置之',function(){return '你轉身回醫館。治好病人，比什麼都有說服力。';}]]},
 {id:'cOfficial',ctx:['move','morning'],w:1,cd:15,cond:function(){return S.region==='xianyang'&&S.fam.fame>=15;},text:function(){return ['一位官員府上的管家登門：「我家大人腹痛三日，請大夫過府。」'];},opts:[['出診',function(){if(S.fam.grudge&&!S.fam.grudge.done&&S.fam.grudge.clues.indexOf('人脈相助')<0){S.fam.grudge.clues.push('人脈相助');S.fam.grudge.ev++;}Med.open({src:'call',ci:Med.caseOf('append'),fee:150});return {screen:'med'};}],['推辭',function(){return '管家臉色一沉，走了。';}]]},
 {id:'cMatch',ctx:['move','morning'],w:2,cd:20,cond:function(){var me=pc();return !me.spouse&&ageOf(me)>=17&&ageOf(me)<40&&S.region!=='road';},text:function(){return ['媒婆扭著腰上門：「哎喲，這麼好的人才還沒婚配？我手上有一門好親事！」'];},opts:[['聽聽看',function(){var me=pc();var g=me.g==='f'?(S.world==='female'&&rand()<0.2?'f':'m'):'f';var p=genPerson({g:g,age:clamp(ageOf(me)+rnd(7)-3,16,45),kind:'npc',job:pick(['trader','scholar','farmer','owner','clerk']),met:1,aff:35,love:20,loc:{r:S.region,pl:'market'}});return {lines:['媒婆說的是'+p.n+'，'+ageOf(p)+'歲，'+JOBS[p.job]+'，性子'+p.pers.join('、')+'。'],focus:p.id,ch:[ch('💬 見一面','talk',{id:p.id}),ch('↩ 再說吧','place')]};}],['婉拒',function(){return '媒婆悻悻地走了。';}]]},
 {id:'cFest',ctx:['morning'],w:1,cd:30,cond:function(){var d=(S.day-1)%DPY;return S.region!=='road'&&(d===2||d===35);},text:function(){var d=(S.day-1)%DPY;return [d===2?'上巳節。城外水邊人頭攢動，祓禊、踏青。':'臘日。家家祭祖、分肉、驅疫。'];},opts:[['帶家人去湊熱鬧',function(){Eng.house().forEach(function(p){p.mood=clamp(p.mood+8,0,100);});Eng.pass(2);return '一家人難得笑得這麼開心。（全家心情+8）';}]]},
 {id:'cOrphan',ctx:['move'],w:1,cd:40,cond:function(){return S.region!=='road'&&ageOf(pc())>=18;},text:function(){return ['巷口蜷著一個三四歲的孩子，餓得哭不出聲。問了一圈，沒有人認得他。'];},opts:[['帶回家收養',function(){var k=genPerson({age:3+rnd(2),sur:S.fam.sur,kind:'fam',hh:1,met:1,aff:40,job:'child'});k.rel=k.g==='m'?'養子':'養女';k.par=[S.pc];pc().kids.push(k.id);addLog('〔家〕收養'+k.n,'家');return '你把孩子抱回了家，給他取名'+k.n+'。從今天起，'+Fam.name()+'多了一口人。';}],['給些吃的',function(){var kk=Eng.foodKeys()[0];if(kk)Inv.add(kk,-1);return '孩子狼吞虎嚥地吃完，跑走了。';}]]},
 /* ---- 家 ---- */
 {id:'kQuarrel',ctx:['morning'],w:2,cd:12,cond:function(){return Eng.house().filter(function(p){return p.id!==S.pc&&ageOf(p)>=6;}).length>=2;},text:function(){var f=Eng.house().filter(function(p){return p.id!==S.pc&&ageOf(p)>=6;});var a=f[0],b=f[1];S.tmp={qa:a.id,qb:b.id};return [a.n+'和'+b.n+'為了一件小事吵得面紅耳赤。'];},opts:[['各打五十大板',function(){[S.tmp.qa,S.tmp.qb].forEach(function(id){People.rel(id,{aff:-1});});return '兩人都不服氣，但總算安靜了。';}],['坐下來聽他們說',function(){Eng.pass(1);[S.tmp.qa,S.tmp.qb].forEach(function(id){People.rel(id,{aff:2,trust:2});});return '你聽完了兩邊的理，一人哄了幾句。晚飯時兩人又有說有笑了。';}]]},
 {id:'kTalent',ctx:['morning'],w:1,cd:30,cond:function(){return Eng.house().some(function(p){return p.par.indexOf(S.pc)>=0&&ageOf(p)>=4&&ageOf(p)<14&&p.expr.length;});},text:function(){var k=Eng.house().filter(function(p){return p.par.indexOf(S.pc)>=0&&ageOf(p)>=4&&ageOf(p)<14&&p.expr.length;})[0];var g=GENES[k.expr[0]];return [k.n+'今天'+(g.show||('顯出了「'+g.n+'」的稟賦'))+'。'];},opts:[['好好栽培',function(){return '你在心裡記下了這件事。';}]]}
];
Ev.cool=function(e){return S.day-(S.evseen[e.id]||-999)>=(e.cd||5);};
Ev.roll=function(ctx){if(S.queue.length)return false;var c=Ev.LIB.filter(function(e){return e.ctx.indexOf(ctx)>=0&&Ev.cool(e)&&(!e.cond||e.cond());});if(!c.length)return false;var tot=c.reduce(function(s,e){return s+e.w;},0);var r=rand()*tot,e=c[0];for(var i=0;i<c.length;i++){r-=c[i].w;if(r<=0){e=c[i];break;}}S.evseen[e.id]=S.day;S.queue.push({go:'ev',a:{id:e.id}});return true;};
Ev.get=function(id){return Ev.LIB.filter(function(e){return e.id===id;})[0];};
NODES.ev=function(a){var e=Ev.get(a.id);if(!e)return NODES.place();var L=e.text();S.evcur=a.id;var c=e.opts.map(function(o,i){return ch(typeof o[0]==='function'?o[0]():o[0],'evc',{id:a.id,i:i});});if(c.length<2&&!e.solo)c.push(ch('（靜觀其變）','evPass',{id:a.id}));if(AI.ready())c.push(ch('✍ 自己決定（輸入）','evFree',{id:a.id}));return Eng.L(L,'',S.place,c,{ev:a.id});};
NODES.evPass=function(a){S.evcur='';return Eng.L([pick(['你沒有多做什麼，只把這件事記在心裡。','你按捺住了，事情就這樣過去了。','你嘆了口氣，轉身去做自己的事。'])],'',S.place,[ch('繼續','place')]);};
NODES.evc=function(a){var e=Ev.get(a.id);var r=e.opts[a.i][1]();S.evcur='';if(r&&r.screen)return r;if(r&&r.lines){var sc=Eng.L(r.lines,r.focus||'',S.place,r.ch||[ch('繼續','place')]);return sc;}addLog('〔事〕'+String(r).slice(0,40),'事');return Eng.L([r],'',S.place,[ch('繼續','place')]);};
NODES.evFree=function(a){return Eng.L(['（在下方輸入框寫下你的決定。）'],'',S.place,[ch('↩ 還是選吧','ev',{id:a.id})]);};
/* ===== 交談 ===== */
var TALK={
 greet:function(p){var T=ta(p),call=Gender.call(p.id);if(p.hh)return pick(['「回來啦？」','「今天累不累？」','「'+pc().n+'，鍋裡給你留了吃的。」']);if(!p.met)return pick(['「你是……？」'+T+'打量著你。','「有事？」']);if(p.love>=50)return '「'+call+'。」'+T+'看見你，眼睛一下子亮了。';if(p.aff>=40)return pick(['「是你啊！」','「來得正好，我正想找你。」']);if(p.aff<0)return '「……又是你。」'+T+'語氣冷淡。';return pick(['「'+call+'。」','「近來可好？」']);},
 chat:function(p){var J={farmer:['今年雨水不錯，就怕秋後蟲多。','地裡的活計，一天不做就荒了。'],trader:['最近布價又漲了。','做買賣，講究眼光。'],guard:['上頭催得緊，兄弟們也難。','差事難辦啊。'],scholar:['近讀〈商君書〉，頗有所得。','律令如山，可人心不是竹簡。'],soldier:['北邊又要打仗了。','軍中缺醫，一場仗下來，死於傷口潰爛的比死於刀下的還多。'],exile:['不知道這輩子還回不回得去。','能活著，就好。'],tradoc:['你那刀圭之術……老夫看不懂，也不服。','望聞問切，是祖宗的法子。'],fangshi:['天道玄微，凡人豈能窺測。','長生之術，確有其事。']};var a=J[p.job]||['日子嘛，一天天過。','你最近在忙什麼？','天氣'+(Eng.season()===3?'冷':'熱')+'，多保重。'];if(p.kind==='named'&&TALK.N[p.id])a=TALK.N[p.id].concat(p.like[0]?['你可知哪裡有好的'+p.like[0]+'？']:[]);else a=a.concat(TALK.G[(p.pers||[])[0]]||[]).concat(['你最近在忙什麼？','聽說城南來了個會用針線縫人的大夫。','今年的粟價，唉。']);var n=p.notes;var c=a.filter(function(x){return x!==n.lastChat&&x!==n.lastChat2;});var t=pick(c.length?c:a);n.lastChat2=n.lastChat;n.lastChat=t;return '「'+t.replace(/^「|」$/g,'')+'」';},
 N:{yingzheng:['寡人昨夜又看了半宿奏簡。','六國……遲早是一家。','你的醫術，從哪裡學來的？','趙國的冬天很冷。寡人記得。','說吧，你想要什麼賞賜？','你不怕寡人？','朝中那些人，各有各的算盤。','你說的那個「消毒」，寡人讓宮人試過了。'],
  mengtian:['今天的糖人做得真好看！','我爹又罵我了，哈哈。','你知道北邊的草原有多大嗎？騎三天馬都看不到頭！','軍中的弟兄們都說你是神醫！','改天我教你騎馬！','這把劍是我祖父傳下來的。','你吃過烤羊腿嗎？北邊的最好吃。','我才不怕疼呢——好吧，有一點。'],
  lisi:['今日天色不錯，宜對弈。','人之賢不肖，譬如鼠矣。','你的醫館，生意如何？','咸陽城裡，處處是棋局。','法者，所以禁暴也。','大夫可知，我最怕什麼？——無趣。','這梅花，再過幾日就開了。','你看人的眼神，像在找病灶。'],
  fusu:['今日讀了一卷詩，想念給你聽。','城南的孩子們，近來可好？','父王他……其實很累。','你給的藥，我按時喝了。','書上說「仁者愛人」，你便是這樣的人吧。','天又冷了。','我想去民間走走，看看真正的天下。','今日的琴，彈得還行嗎？'],
  hanfei:['我、我近日在寫一卷新書。','世之治亂，在法、術、勢。','你、你說話很慢，我喜歡。','韓國……很小。','這竹簡，借、借你看。','人心難測，法、法可測。','你的解剖圖……我、我還想再看。','墨又用完了。'],
  jingke:['來，喝一碗！','劍要快，人要義。','高漸離的筑，天下第一。','衛國的酒沒有這裡的烈。','你的手很穩，適合握劍——也適合握刀子救人。','我這條命，是撿回來的。','一諾千金，懂嗎？','今晚的月亮真圓。'],
  xuanye:['……','有人跟著你。我處理了。','窗台上的東西，收到了嗎。','影子不需要名字。','你該早點睡。','傷口……好了。','今晚別出門。','……謝謝。'],
  xiawuju:['刀子割人，成何體統。','湯藥才是正道。','你那酒精……有點意思。','宮裡的病，可不是市井的病。','老夫行醫三十年，沒見過你這種治法。'],
  xufu:['海上有仙山，名曰蓬萊。','長生之術，你信不信？','你的醫術，莫非也是仙術？','天機不可洩露。','大王對長生，很有興趣。'],
  zhaogao:['大夫辛苦了。','宮中耳目眾多，大夫說話要小心。','奴婢只是替大王跑腿的。','大夫的醫術，真是神乎其技啊。','有空，來奴婢府上坐坐。'],
  gaojianli:['……想聽一曲嗎？','荊卿又喝醉了。','筑聲，是心聲。','易水的水，很冷。','你笑起來很好看。'],
  mengyi:['法者，所以禁暴也。','家兄常提起你。','廷尉署近日多事。','證據不足，不可妄斷。','你的刀圭……若用在刑訊上，後果難料。'],
  baqing:['巴蜀的丹砂，比金子還貴。','做生意，講究信字。','咸陽的酒，烈是烈，卻不夠香。','你開醫館？改天我投筆銀子。','遠道而來，最怕人騙。'],
  nanheng:['湯藥才是正道——你那刀子，太狠。','楚地潮濕，傷寒最多。','你的酒精……我試過了，有用。','別以爲西醫就能壓過我。','針砭與刀圭，或許可以並用。'],
  yanshu:['齊國的海風，和這裡不一樣。','使團裡的事，不宜多問。','你可聽過呂相國與齊國的舊事？','這梅花，像故鄉的一樣。','……我只是過客。'],
  zhengguo:['渠成，則關中無饑。','挖土的事，比說話實在。','韓人在秦，當小心。','水土不服，多有腰腿疾。','你懂醫，可知民病半因饑寒。'],
  aying:['太后今日心情不好……','大夫，宮裡有人發燒。','我什麼都不知道。真的。','這糖人……可以給我嗎？','別告訴別人我跟你說過話。']},
 G:{開朗:['哈哈，今天心情真好！','走，一起去看熱鬧？'],沉默:['……嗯。','你說，我聽著。'],暴躁:['煩死了！','別惹我。'],溫和:['慢慢來，不急。','你也要照顧好自己。'],精明:['這事兒，得算計算計。','無利不起早嘛。'],狡猾:['嘿嘿，大夫好啊。','有什麼好處，記得分我一份。'],仗義:['有事儘管開口！','朋友有難，豈能不管。'],熱心:['吃過了嗎？我家剛蒸了餅。','有什麼要幫忙的？'],刻薄:['哼。','你也配？'],多疑:['你打聽這個做什麼？','人心隔肚皮。'],正直:['做人要問心無愧。','不義之財，不可取。'],膽小:['最近外頭不太平……','我、我什麼都沒看見。'],貪財:['有錢能使鬼推磨。','最近手頭緊啊。']}
};
NODES.talk=function(a){var id=a.id;var p=P(id);if(!p||!p.alive)return NODES.place();var first=!p.met;People.meet(id);Eng.keep(id);S.focus=id;
 var off=function(){var L=[[id,TALK.greet(p)]];if(first&&p.kind==='named'){L.push((P(id).sub||NAMED[id].sub)+'。'+(P(id).bio||NAMED[id].bio));}var q=Thread.quote(id);if(q&&!first)L.push([id,q]);if(p.hh&&ageOf(p)>=3)L.push('（心聲）'+People.thought(p));return Eng.L(L,id,S.place,NODES.talkCh(id));};
 if(AI.ready()&&!a.off){return {async:{type:'talk',id:id,topic:a.topic||'閒聊'},fb:off};}return off();};
NODES.talkCh=function(id){var p=P(id),me=pc();var c=[ch('閒聊','talkT',{id:id,k:'chat'}),ch('問近況','talkT',{id:id,k:'news'})];if(Rom.ARC[id]&&Rom.ready(id))c.unshift(ch('💞 '+Rom.title(id),'rom',{id:id}));if(p.ill.length||(p.kind==='named'&&NAMED[id].ail&&p.met&&!p.notes.ailCured&&p.trust>=20))c.push(ch('🩺 替'+ta(p)+'診治','talkT',{id:id,k:'heal'}));var cl=S.calls.filter(function(v){return v.id===id;})[0];if(cl&&Med.caseOf(cl.cs)>=0)c.push(ch('🏠 應邀出診（'+CASES[Med.caseOf(cl.cs)].dx+'）','talkT',{id:id,k:'call'}));
 if(Object.keys(S.inv).some(function(k){return ITEMS[k]&&(ITEMS[k].gift||ITEMS[k].k==='food')&&S.inv[k]>0&&!ITEMS[k].hide;}))c.push(ch('🎁 送禮','gift',{id:id}));
 if(p.love>=25&&p.spouse!==S.pc&&!p.confessed&&!p.hh&&ageOf(p)>=16&&ageOf(me)>=16)c.push(ch('💗 表白心意','confess',{id:id}));if(!People.canPropose(id))c.push(ch('💍 '+Rule.marryWord(me,p).replace(/^結為/,'')+'／求親','propose',{id:id}));
 if(p.aff>=30&&!p.hh)c.push(ch('🌸 邀'+ta(p)+'同遊','talkT',{id:id,k:'date'}));if(FW.secretsOf().length&&p.trust>=35)c.push(ch('🔏 吐露秘密','talkT',{id:id,k:'secret'}));c.push(ch('告辭','place'));return c;};
NODES.talkT=function(a){var id=a.id,p=P(id),me=pc();var L=[];var k=a.k;
 if(AI.ready()&&k!=='heal'&&k!=='call'){var tp={chat:'閒聊',news:'問近況',date:'邀約同遊',secret:'主角想吐露秘密'}[k];return {async:{type:'talk',id:id,topic:tp},fb:function(){return NODES.talkT({id:id,k:k,off:1,_o:1});}};}
 if(k==='chat'){Eng.pass(1);L.push([id,TALK.chat(p)]);if(p.notes.tk!==S.day){p.notes.tk=S.day;People.rel(id,{aff:2,trust:1},'與'+me.n+'閒聊');if(p.love<60&&p.aff>=35&&rand()<0.3)People.rel(id,{love:2});}}
 else if(k==='news'){L.push([id,'「'+People.thought(p).replace(/^（|）$/g,'')+'」']);if(p.ill.length)L.push(ta(p)+'說著咳了兩聲——看起來是'+Ill.str(p)+'。');if(p.kind==='named'&&NAMED[id].ail&&!p.notes.ailCured)L.push('你注意到'+ta(p)+'似乎有'+NAMED[id].ail+'的毛病。');}
 else if(k==='heal'){if(p.ill.length){Med.open({pid:id,src:'call',fee:p.kind==='named'?60:15});return {screen:'med'};}if(p.kind==='named'){var ci=Med.caseOf({頭痛失眠:'fever',舊箭傷:'arrow',胃疾:'diarrhea',寒症:'lung',心悸:'fever',舊毒:'poison',刀傷:'cut',舊傷隱痛:'fracture',旅途風寒:'fever',過勞心悸:'fever',思鄉失眠:'fever',腰腿勞損:'fracture',宮寒體弱:'fever'}[NAMED[id].ail]||'fever');p.notes.ailTry=S.day;Med.open({pid:'',ci:ci,src:'call',fee:40,cb:'ail:'+id});return {screen:'med'};}}
 else if(k==='call'){var cl=S.calls.filter(function(v){return v.id===id;})[0];if(cl){S.calls=S.calls.filter(function(v){return v!==cl;});Eng.pass(1);People.rel(id,{aff:4,trust:4},me.n+'應邀到我家出診');Med.open({pid:'',ci:Med.caseOf(cl.cs),src:'call',fee:15+Fam.tier()*5});return {screen:'med'};}}
 else if(k==='date'){Eng.pass(2);People.rel(id,{aff:4,love:3},'和'+me.n+'同遊');me.mood=clamp(me.mood+6,0,100);L.push('你們沿著'+(S.region==='frontier'?'河灘':'渭水')+'走了很久，說了很多話。');L.push([id,p.love>=40?'「……下回，還一起來吧。」':'「今天很開心。」']);}
 else if(k==='secret'){var f=FW.secretsOf().filter(function(x){return x.kn.indexOf(id)<0;})[0];if(!f)L.push('你想說的，'+ta(p)+'都已經知道了。');else{Seal.told(id,f);People.rel(id,{trust:6},me.n+'把秘密託付給我');L.push('你壓低聲音，把「'+f.t+'」告訴了'+p.n+'。');L.push([id,'「……我知道了。這件事，我不會對任何人說。」']);}}
 return Eng.L(L,id,S.place,NODES.talkCh(id));};
NODES.gift=function(a){var ks=Object.keys(S.inv).filter(function(k){return ITEMS[k]&&(ITEMS[k].gift||ITEMS[k].k==='food'||ITEMS[k].k==='mat')&&S.inv[k]>0&&!ITEMS[k].hide;}).sort(function(x,y){return (ITEMS[y].gift?1:0)-(ITEMS[x].gift?1:0);}).slice(0,6);return Eng.L(['送什麼給'+cn(a.id)+'？'],a.id,S.place,ks.map(function(k){return ch(ITEMS[k].n+'（'+S.inv[k]+'）','giveGift',{id:a.id,k:k});}).concat([ch('↩','talk',{id:a.id,off:1})]));};
NODES.giveGift=function(a){var p=P(a.id);var it=ITEMS[a.k];Inv.add(a.k,-1);var like=p.like.some(function(l){return it.n.indexOf(l)>=0||l.indexOf(it.n.slice(-1))>=0;});var g=like?{aff:7,love:3}:(it.gift?{aff:3,love:1}:{aff:1});if(p.notes.gd===S.day)g={aff:1};p.notes.gd=S.day;People.rel(a.id,g,'收到'+pc().n+'送的'+it.n);return Eng.L([[a.id,like?'「這是……我最喜歡的'+it.n+'！你怎麼知道？」':'「謝謝。」']],a.id,S.place,NODES.talkCh(a.id));};
NODES.confess=function(a){var p=P(a.id),me=pc();var ok=p.love>=45&&p.aff>=35;p.confessed=1;Eng.pass(1);if(ok){People.rel(a.id,{love:8,aff:5},me.n+'向我表白，我答應了');p.lover=1;FW.add(me.n+'與'+p.n+'互許心意',[S.pc,a.id],S.pc,{});}else{People.rel(a.id,{aff:-3},me.n+'向我表白，我拒絕了');p.confessed=0;p.notes.rej=S.day;}
 var sc=Eng.L(ok?['你把話說出了口。',[a.id,'「……我等這句話，等了很久。」']]:['你把話說出了口。',[a.id,'「對不起……我一直只把你當作'+(p.aff>=30?'知己':'相識')+'。」']],a.id,S.place,[ch('繼續','place')]);return End.milestone(ok?'confessOk':'confessNo',{id:a.id},sc);};
NODES.propose=function(a){var p=P(a.id),me=pc();var why=People.canPropose(a.id);if(why)return Eng.L(['（'+why+'）'],a.id,S.place,NODES.talkCh(a.id));var cost=30+Fam.tier()*40+(p.kind==='named'?60:0);var w=Rule.marryWord(me,p);
 if(S.gold<cost)return Eng.L([[a.id,'「我願意。可是……」'],'婚事要三媒六聘，至少得備'+cost+'兩。你的錢不夠。'],a.id,S.place,NODES.talkCh(a.id));
 return Eng.L(['你鄭重地向'+p.n+'提出婚事（'+w+'，聘禮'+cost+'兩）。',[a.id,'「……好。」']],a.id,S.place,[ch('💍 擇日成婚','wed',{id:a.id,cost:cost}),ch('再等等','talk',{id:a.id,off:1})]);};
NODES.wed=function(a){Inv.gold(-a.cost);var w=People.marry(a.id);Eng.pass(2);var p=P(a.id);var sc=Eng.L(['紅燭高燒。你與'+p.n+w+'。',[a.id,'「往後的日子，我們一起過。」'],(p.hh?p.n+'搬進了'+Fam.name()+'的家。':'')],a.id,S.place,[ch('繼續','place')]);return End.milestone('marry',{id:a.id},sc);};
/* ===== 家族事件 ===== */
NODES.birth=function(a){var ks=a.ids.map(P).filter(Boolean);var L=[(a.mo===S.pc?'你':cn(a.mo))+'生下了'+(ks.length>1?'一對雙生兒':'一個'+(ks[0].g==='m'?'男孩':'女孩'))+'！'];ks.forEach(function(k){var ex=k.expr.map(function(g){return GENES[g].n;});L.push(k.n+'：'+(k.look.hairN||'')+(ex.length?'；似有「'+ex.join('、')+'」之相':'')+'；乳名「'+(k.milk||'')+'」。');});
 return Eng.L(L,'',S.place,ks.map(function(k){return ch('✎ 為'+k.n+'改名','nameKid',{id:k.id});}).concat([ch('就叫這名字','place')]));};
NODES.nameKid=function(a){return {dialogName:{id:a.id}};};
NODES.comeOfAge=function(a){var p=P(a.id);if(!p||!p.alive)return NODES.place();var L=[p.n+'長大了，十四歲，到了該決定前程的年紀。（醫'+p.sk.med+' 文'+p.sk.lit+' 農'+p.sk.farm+' 武'+p.sk.mart+'）'];
 return Eng.L(L,'',S.place,[ch('跟我學醫','coaDo',{id:a.id,k:'med'}),ch('讀書，將來入仕','coaDo',{id:a.id,k:'lit'}),ch('在家幫忙種地','coaDo',{id:a.id,k:'farm'}),ch('學做買賣','coaDo',{id:a.id,k:'trade'}),ch('讓'+ta(p)+'自己選','coaDo',{id:a.id,k:'free'})]);};
NODES.coaDo=function(a){var p=P(a.id);var k=a.k==='free'?pick(['med','lit','farm','trade','mart']):a.k;p.sk[k]=clamp(p.sk[k]+10,0,100);p.job={med:'apprentice',lit:'scholar',farm:'farmer',trade:'trader',mart:'xia'}[k];if(k==='med'&&S.fam.clinic.apps.indexOf(p.id)<0)S.fam.clinic.apps.push(p.id);People.rel(p.id,{aff:a.k==='free'?6:2});return Eng.L([p.n+(a.k==='free'?'想了很久，說想'+{med:'學醫',lit:'讀書',farm:'種地',trade:'做買賣',mart:'練武'}[k]+'。':'點點頭。')],'',S.place,[ch('繼續','place')]);};
NODES.funeral=function(a){var p=P(a.id);var L=[p.n+'走了（'+(a.why||'')+'），享年'+ageOf(p)+'。'];Eng.house().forEach(function(q){q.mood=clamp(q.mood-12,0,100);});if(a.id==='master'){Inv.add('notes',Inv.has('notes')?0:1);L.push('師父留下了一箱手札和一把柳葉刀。');}if(p.spouse===S.pc)L.push('你守著空了一半的床，很久很久沒有睡著。');return Eng.L(L,'',S.place,[ch('送'+ta(p)+'最後一程','place')]);};
NODES.poisoned=function(){var sick=Eng.house().filter(function(p){return Ill.has(p,'poison');}).sort(function(a,b){return Ill.get(b,'poison').sev-Ill.get(a,'poison').sev;});var L=['一家人上吐下瀉，'+sick.map(function(p){return p.id===S.pc?'你':p.n;}).join('、')+'臉色發青。'];var c=[];
 if(sick.length){c.push(ch('🩺 先救'+(sick[0].id===S.pc?'自己':sick[0].n),'treat',{id:sick[0].id}));c.push(ch('💧 給全家灌鹽糖水催吐','poisonAll'));}c.push(ch('……熬過去','place'));return Eng.L(L,'',S.place,c);};
NODES.poisonAll=function(){Eng.pass(1);var ors=Inv.has('ors');Eng.house().forEach(function(p){if(Ill.has(p,'poison'))Ill.cure(p,'poison',ors?3:1);});if(ors)Inv.add('ors',-1);if(Inv.has('antidote')){Inv.add('antidote',-1);Eng.house().forEach(function(p){Ill.cure(p,'poison',2);});}return Eng.L(['你讓每個人都吐乾淨，再一口口灌下'+(ors?'鹽糖水':'溫水')+'。'+(ors?'到了夜裡，大家總算緩過來了。':'情況稍有好轉。')],'',S.place,[ch('繼續','place')]);};
NODES.disgExpose=function(a){var p=P(a.id);return Eng.L([[a.id,'「你……'+(pc().g==='f'?'你是女子？':'你是男子？')+'」'],p.n+'盯著你的喉頭和手腕，眼神從疑惑變成了震驚。'],a.id,S.place,[ch('求'+ta(p)+'替我保密','dxDo',{id:a.id,k:'beg'}),ch('索性承認，不再隱瞞','dxDo',{id:a.id,k:'admit'}),ch('威脅'+ta(p)+'閉嘴','dxDo',{id:a.id,k:'threat'})]);};
NODES.dxDo=function(a){var p=P(a.id);if(a.k==='beg'){Gender.tell(a.id);People.rel(a.id,{trust:4});return Eng.L([[a.id,'「……我什麼也沒看見。」']],a.id,S.place,[ch('繼續','place')]);}if(a.k==='admit'){Gender.expose(a.id);return Eng.L(['消息傳開了。有人驚嘆，有人非議'+(S.world==='male'&&pc().g==='f'?'：「女人也敢……」':'。')],a.id,S.place,[ch('繼續','place')]);}
 Gender.tell(a.id);People.rel(a.id,{aff:-10,trust:-8});Bond.apply(a.id,{e:{怨恨:8,戒備:10}});return Eng.L([p.n+'臉色發白，點了點頭。但你知道，這根刺埋下了。'],a.id,S.place,[ch('繼續','place')]);};
NODES.paceMeet=function(a){var p=P(a.id);if(!p||!p.alive)return NODES.place();p.here={d:S.day,per:S.per,pl:S.place};Eng.keep(a.id);var L=[(p.kind==='named'?(P(a.id).sub||NAMED[a.id].sub):People.label(a.id))+'朝你走了過來。'];if(p.kind==='named')L.push((P(a.id).bio||NAMED[a.id].bio));return Eng.L(L,a.id,S.place,[ch('💬 上前搭話','talk',{id:a.id}),ch('↩ 不理會','place')]);};
NODES.visit=function(a){var p=P(a.id);if(!p||!p.alive)return NODES.place();p.here={d:S.day,per:S.per,pl:S.place};Eng.keep(a.id);Pace.mark(a.id);var L=[p.n+'來找你了。'];var c=[];
 if(p.love>=60&&!p.confessed&&p.spouse!==S.pc&&!pc().spouse){p.confessed=1;p.lover=1;L.push([a.id,'「有些話憋了很久……我喜歡你。」']);People.note(a.id,'向'+pc().n+'表白','crit');var sc=Eng.L(L,a.id,S.place,[ch('💗 我也是','visitAns',{id:a.id,ok:1}),ch('對不起','visitAns',{id:a.id,ok:0})]);return sc;}
 if(p.aff>=50&&rand()<0.5){var it=pick(['cake','fruit','honey','wine','cloth','osm']);Inv.add(it,1);L.push([a.id,'「路過'+(PLACES[p.loc&&p.loc.pl]||{n:'集上'}).n+'，順手給你帶了'+ITEMS[it].n+'。」']);}
 else L.push([a.id,'「沒什麼事，就是想來看看你。」']);return Eng.L(L,a.id,S.place,[ch('💬 聊聊','talk',{id:a.id}),ch('送'+ta(p)+'出門','place')]);};
NODES.visitAns=function(a){var p=P(a.id);if(a.ok){People.rel(a.id,{love:8,aff:4});FW.add(pc().n+'與'+p.n+'互許心意',[S.pc,a.id],S.pc,{});return End.milestone('confessOk',{id:a.id,by:'npc'},Eng.L([[a.id,'「……真的？」'],ta(p)+'笑得像個孩子。'],a.id,S.place,[ch('繼續','place')]));}p.lover=0;People.rel(a.id,{aff:-4,love:-10});return Eng.L([[a.id,'「……我明白了。」'],ta(p)+'低著頭走了。'],a.id,S.place,[ch('繼續','place')]);};
NODES.outing=function(a){var p=P(a.id);S.invites=S.invites.filter(function(v){return !(v.id===a.id&&v.day===S.day);});if(!p||!p.alive)return NODES.place();p.here={d:S.day,per:S.per,pl:S.place};Eng.keep(a.id);Eng.pass(1);People.rel(a.id,{aff:5,love:3},'和'+pc().n+'赴約同遊');return Eng.L(['你如約來到'+PLACES[S.place].n+'。'+p.n+'已經在等了。',[a.id,'「我還怕你不來。」']],a.id,S.place,[ch('💬 聊聊','talk',{id:a.id}),ch('↩','place')]);};
/* ===== 醫術引起的反應 ===== */
NODES.evTradoc=function(){S.evseen.tradocEnvy=S.day;var w=alive('xiawuju')?'xiawuju':'';var nm=w?cn(w):'城東的老醫者';if(w){P(w).met=1;P(w).here={d:S.day,per:S.per,pl:S.place};}return Eng.L([nm+'登門，捋著鬍子冷笑：「聽說你用刀子割人、用針線縫肉？今日當著街坊的面，你我各治一個病人，看誰的法子靈。」'],w,S.place,[ch('應戰','tradocDo',{ok:1}),ch('「醫者治病，不是比武。」','tradocDo',{ok:0})]);};
NODES.tradocDo=function(a){var w=alive('xiawuju')?'xiawuju':'';if(!a.ok){if(w)People.rel(w,{trust:2,aff:-1});return Eng.L(['對方哼了一聲走了。旁人議論你是不敢。'],w,S.place,[ch('繼續','place')]);}var me=pc();var win=me.sk.med+rnd(30)>70;if(win){S.fam.fame+=4;if(w)People.rel(w,{trust:6,aff:2},'輸給'+me.n+'，心服口服');WS.log(me.n+'與'+(w?cn(w):'老醫者')+'比試，以刀圭之術勝出','起因：傳統醫者不服西醫','你所為');return Eng.L(['你的病人當天就能下地，對方的病人還在喝符水。','老醫者盯著你縫的傷口看了很久：「……這針法，是誰教你的？」（名聲+4）'],w,S.place,[ch('繼續','place')]);}
 S.fam.notor=(S.fam.notor||0)+2;if(w)People.rel(w,{aff:-3});return Eng.L(['你的病人傷口紅腫，對方的卻平安無事。街坊們搖頭散去。'],w,S.place,[ch('繼續','place')]);};
NODES.evFangshi=function(){S.evseen.fangshi=S.day;var f=alive('xufu')&&!P('xufu').away?'xufu':'';if(f){P(f).met=1;P(f).here={d:S.day,per:S.per,pl:S.place};}return Eng.L([(f?cn(f):'一個方士')+'帶著一群人堵在門口，舉著桃木劍：「此人剖人腹、飲人血，是妖！是邪術！」','人群騷動起來，有人撿起了石頭。'],f,S.place,[ch('當眾救治一個病人自證','fsDo',{k:'show'}),ch('據理力爭','fsDo',{k:'argue'}),ch('暫避鋒芒，關門閉館','fsDo',{k:'hide'})]);};
NODES.fsDo=function(a){var me=pc();var L=[];if(a.k==='show'){var ok=me.sk.med+rnd(40)>65;if(ok){S.fam.fame+=5;S.fam.notor=Math.max(0,(S.fam.notor||0)-4);L.push('你當著眾人的面，為一個膿腫潰爛的乞丐切開引流、包紮。三日後他能走了——流言不攻自破。（名聲+5）');}else{S.fam.notor+=3;L.push('病人疼得慘叫，人群更怕了。');}}
 else if(a.k==='argue'){if(me.sk.lit+rnd(40)>60){L.push('你一條條駁斥，方士詞窮，悻悻離去。');S.fam.notor=Math.max(0,(S.fam.notor||0)-2);}else{L.push('你說得越多，人們越覺得玄。');S.fam.notor+=2;}}
 else{Eng.pass(6);S.fam.fame=Math.max(0,S.fam.fame-2);L.push('你閉館一日。風頭漸漸過去了，但生意也冷清了不少。');}
 if((S.fam.notor||0)>=14&&!S.flags.heldOnce){S.flags.heldOnce=1;S.flags.held=S.day;L.push('當晚，官府的人來了：「有人告你行妖術。跟我們走一趟。」');return Eng.L(L,'',S.place,[ch('……','held')]);}return Eng.L(L,'',S.place,[ch('繼續','place')]);};
NODES.evCourt=function(){S.flags.palace=1;var y=alive('yingzheng')?'yingzheng':(alive('fusu')?'fusu':'');if(!y)return NODES.place();People.meet(y);return Eng.L(['宮中來人：「大王頭疾又犯，太醫束手。聽聞城南有位用奇術的醫者——隨我入宮！」'],'',S.place,[ch('入宮診治','courtCure',{id:y}),ch('推辭','place')]);};
NODES.courtCure=function(a){S.place='palace';var p=P(a.id);p.here={d:S.day,per:S.per,pl:'palace'};Eng.keep(a.id);var me=pc();Eng.pass(2);var ok=me.sk.med+rnd(40)>60;if(ok){People.rel(a.id,{trust:12,aff:6},me.n+'治好了我的'+NAMED[a.id].ail);p.notes.ailCured=1;Idn.apply({k:'medoff',to:'侍醫',by:a.id},true);WS.log(me.n+'入宮為'+cn(a.id)+'治病，被任為侍醫','起因：太醫束手','你所為');return Eng.L(['你以聽診筒聽過心肺，又問清起居，開了退熱止痛的柳皮散，叮囑少飲酒、早安寢。',[a.id,'「……三年來，寡人第一次睡到天明。」'],'你被任為侍醫，可自由出入宮禁。'],a.id,'palace',[ch('💬 與'+cn(a.id)+'交談','talk',{id:a.id}),ch('↩','place')]);}
 People.rel(a.id,{trust:-4});return Eng.L(['你的法子沒有見效。'+cn(a.id)+'揮揮手讓你退下。'],a.id,'palace',[ch('↩','place')]);};
NODES.evAccuse=function(){var g=People.present()[0];return Eng.L(['死者的家屬抬著屍體堵在醫館門口哭天搶地：「庸醫殺人！償命！」'],'',S.place,[ch('賠銀子了事（50 兩）','accDo',{k:'pay'}),ch('上公堂說清楚','accDo',{k:'court'})]);};
NODES.accDo=function(a){if(a.k==='pay'){Inv.gold(-Math.min(S.gold,50));return Eng.L(['家屬收了錢，罵罵咧咧地走了。'],'',S.place,[ch('繼續','place')]);}var me=pc();if(me.sk.med+me.sk.lit+rnd(30)>90||S.fam.fame>=30){S.fam.fame+=1;return Eng.L(['你在公堂上講清病情凶險、處置無誤。縣令判你無罪。'],'',S.place,[ch('繼續','place')]);}S.flags.held=S.day;return Eng.L(['縣令拍案：「先收監，再議！」'],'',S.place,[ch('……','held')]);};
/* ===== 師父 ===== */
NODES.seekMaster=function(){Eng.pass(2);pc().sta-=15;S.flags.mtry=(S.flags.mtry||0)+1;var m=P('master');var can=(S.flags.mtry>=2||S.flags.masterHint)&&rand()<0.6||S.flags.mtry>=4;
 if(!can)return Eng.L(['雲霧太濃，你在山裡繞了兩個時辰，只找到幾株草藥。'],'',S.place,[ch('↩','place')]).ch&&(Inv.add('herb',1),Eng.L(['雲霧太濃，你在山裡繞了兩個時辰，只找到一株草藥。'],'',S.place,[ch('↩','place')]));
 if(!m){m=genPerson({id:'master',g:'m',age:72,sur:'青囊',gn:'子',kind:'npc',job:'tradoc',met:1,aff:20,trust:10,pers:['溫和','正直'],loc:{r:'frontier',pl:'mountain'}});m.n='青囊子';m.title='隱士';m.sk.med=95;FW.add('隱士青囊子年輕時遠遊極西「大秦國」，學得解剖刀圭之術',['master'],'master',{k:'master',secret:1,pcKnows:false});}
 S.flags.masterMet=1;m.met=1;m.loc={r:'frontier',pl:'mountain'};m.here={d:S.day,per:S.per,pl:'mountain'};Eng.keep('master');
 if(S.flags.intro==='std')return Eng.L(['草廬還是老樣子。師父在院裡曬藥，抬頭看見你，愣了一下，笑了。',['master','「怎麼，世道太難，想回來了？」']],'master',S.place,[ch('🧓 向師父學醫','learn'),ch('💬 與師父說話','talk',{id:'master'})]);
 return Eng.L(['雲霧深處有一間草廬。一個白鬚老人正把一隻斷了腿的山雞綁上小小的夾板。',['master','「迷路了？……哦，你看得懂我在做什麼？」']],'master',S.place,[ch('🙇 拜師學醫','learn'),ch('💬 說話','talk',{id:'master'})]);};
NODES.learn=function(){var m=P('master');if(!m||!m.alive)return Eng.L(['草廬空了。'],'',S.place,[ch('↩','place')]);var me=pc();Eng.pass(2);me.sta-=10;People.rel('master',{aff:2,trust:2});if(!S.flags.disciple){S.flags.disciple=1;m.title='師父';if(!Inv.has('steth'))Inv.add('steth',1);addLog('〔師〕拜青囊子為師','師');FW.learn(S.pc,FW.byK('master').id,100,'told');}
 var next=TECH_ORDER.filter(function(t){return !S.fam.tech[t]&&t!=='incant'&&t!=='bleed'&&t!=='herbs';})[0];me.sk.med=clamp(me.sk.med+3,0,95);var L=[];
 if(next&&(TECH_BASIC.indexOf(next)>=0||me.sk.med>=45)){S.fam.tech[next]=1;L.push('師父教你「'+TECHS[next].n+'」：'+TECHS[next].d+'。（習得新技法，醫+3）');if(next==='alco'&&!Inv.has('still')){Inv.add('still',1);L.push('師父把一套陶甑蒸餾器送給你：「酒要蒸三遍。」');}}
 else L.push('師父讓你剖了一隻野兔，講了一下午的經絡、血管和臟腑。（醫+3）');if(!Inv.has('notes')&&me.sk.med>=50){Inv.add('notes',1);L.push('師父把一卷手札交給你：「你可以出師了。」');}
 return Eng.L(L,'master',S.place,[ch('繼續學','learn'),ch('💬 與師父說話','talk',{id:'master'}),ch('↩','place')]);};
/* ===== 童年（嬰兒開局／幼年繼承人） ===== */
NODES.childYear=function(){var me=pc();var a=ageOf(me);if(a>=14){S.flags.babyStart=0;return Eng.L(['你'+a+'歲了。從今往後，你的每一天都由自己作主。'],'',S.place,[ch('長大成人','place')]);}
 var L=['你'+a+'歲。這一年，你想怎麼過？（醫'+me.sk.med+' 文'+me.sk.lit+' 農'+me.sk.farm+' 武'+me.sk.mart+'）'];var c=[ch('📖 跟著大人識字讀書','cyDo',{k:'lit'}),ch('🌾 幫家裡幹活','cyDo',{k:'farm'}),ch('🤸 和鄰家孩子瘋玩','cyDo',{k:'play'})];if(S.fam.tech.alco||Eng.house().some(function(p){return p.sk.med>=30&&p.id!==S.pc;}))c.push(ch('🩺 跟著學醫','cyDo',{k:'med'}));c.push(ch('🥋 習武強身','cyDo',{k:'mart'}));if(a<3)c=[ch('（咿咿呀呀地長大）','cyDo',{k:'baby'})];return Eng.L(L,'',S.place,c);};
NODES.cyDo=function(a){var me=pc();var k=a.k;var L=[];if(k==='play'){me.at.cha=clamp(me.at.cha+1,1,20);me.at.con=clamp(me.at.con+1,1,20);var f=genPerson({age:ageOf(me),kind:'npc',job:'child',met:1,aff:40,loc:{r:S.region,pl:S.region==='frontier'?'village':'market'}});L.push('你交了個好朋友：'+f.n+'。');}else if(k==='baby'){me.at.con=clamp(me.at.con+(rand()<0.5?1:0),1,20);}else{me.sk[k]=clamp(me.sk[k]+6+(me.tal[k]?4:0),0,100);if(k==='lit')me.at.wit=clamp(me.at.wit+1,1,20);if(k==='mart'||k==='farm')me.at.con=clamp(me.at.con+1,1,20);if(k==='med')S.fam.tech.wash=1;}
 var r=Eng.skip(DPY);L.push('一年過去了。');r.lines.slice(-3).forEach(function(x){L.push(x);});if(S.queue.length)return Eng.L(L,'',S.place,[ch('繼續','place')]);return Eng.L(L,'',S.place,[ch('下一年','childYear')]);};
/* ===== 歷史大事（玩家可影響） ===== */
var History={};
History.doy=function(){return (S.day-1)%DPY;};
History.at=function(yb,doy){return Eng.yb()===yb&&History.doy()>=doy;};
History.once=function(k){if(S.hist.done[k])return false;S.hist.done[k]=S.day;return true;};
History.tick=function(){var y=Eng.yb(),H=S.hist;
 if(y<=238&&History.once('laoai')&&S.startBC>238)WS.log('長信侯嫪毐作亂，被秦王平定','起因：嫪毐私通太后、謀立私子','史');
 if(y<=237&&History.once('lvOut')&&S.startBC>237){var lv=P('lvbuwei');if(lv&&lv.alive){lv.title='文信侯';lv.office=0;}var zj=P('zhaoji');if(zj)zj.away=1;WS.log('秦王親政，罷免相國呂不韋；太后遷居雍城','起因：嫪毐之亂牽連','史');}
 if(y<=235&&History.once('lvDie')){var lv2=P('lvbuwei');if(lv2&&lv2.alive&&!(S.mis&&S.mis.saved)){People.die('lvbuwei','飲鴆自盡');WS.log('呂不韋飲鴆而死','起因：秦王遷其蜀地','史');}}
 if(y<=233&&History.once('hanfeiIn')){var h=P('hanfei');h.away=0;WS.log('韓國公子韓非出使入秦','起因：秦攻韓，韓王遣使','史');}
 if(History.at(233,22)&&History.once('hanfeiDie')){var hf=P('hanfei');if(H.hanfeiSaved){WS.log('韓非出獄，留秦著書','起因：有人為他奔走','你所為');}else if(hf.met&&hf.aff>=30&&S.region==='xianyang'){S.hist.done.hanfeiDie=0;if(History.once('hanfeiAsk'))S.queue.push({go:'histHanfei',stop:1});}else{People.die('hanfei','雲陽獄中飲毒');WS.log('韓非死於雲陽獄','起因：李斯、姚賈進讒','史');}}
 if(y<=230&&History.once('hanFall'))WS.log('秦滅韓','起因：秦王掃六合','史');
 if(y<=228&&History.once('zhaoFall'))WS.log('秦破趙都邯鄲','起因：王翦伐趙','史');
 if(History.at(227,12)&&History.once('jingke')){var j=P('jingke');if(j.alive){if(j.met&&j.aff>=40&&S.region==='xianyang'){S.queue.push({go:'histJingke',stop:1});}else{People.die('jingke','刺秦不成，死於咸陽宮');WS.log('燕國刺客荊軻於咸陽宮行刺秦王，未成被誅','起因：燕太子丹遣刺客','史');}}}
 if(y<=221&&History.once('unify')){WS.log('秦滅齊，天下一統；秦王稱「始皇帝」','起因：十年征戰','史');}
 if(y<=219&&History.once('xufu')){var x=P('xufu');if(x&&x.alive){x.away=1;x.loc={r:'gone',pl:''};}WS.log('方士徐福率童男童女東渡求仙','起因：始皇求長生','史');}
 if(y<=218&&History.once('gaojianli')){var g=P('gaojianli');if(g&&g.alive){People.die('gaojianli','以筑擊始皇不中被誅');}WS.log('樂師高漸離以筑擊始皇，不中被誅','起因：為荊軻報仇','史');}
 if(History.at(213,5)&&History.once('burn')){if(S.region==='xianyang'||Inv.has('notes')||Inv.has('lawbook')||Inv.has('bamboo'))S.queue.push({go:'histBurn',stop:1});WS.log('焚書令下：非秦記、醫藥卜筮種樹之書皆燒','起因：李斯奏議','史');}
 if(y<=212&&History.once('keng'))WS.log('咸陽坑殺諸生四百六十餘人','起因：方士侯生、盧生誹謗而逃','史');
 if(History.at(H.zdie||210,18)&&History.once('shaqiu')){var yz=P('yingzheng');if(yz.alive){var close=pc().medoff>=3||yz.trust>=50||(P('fusu').alive&&P('fusu').trust>=50);if(close&&S.region==='xianyang')S.queue.push({go:'histShaqiu',stop:1});else History.shaqiu(false);}}
 if(y<=209&&History.once('chensheng')){S.flags.bandit=S.day;WS.log(H.alt==='fusu'?'大澤鄉戍卒鬧事，旋被扶蘇安撫':'陳勝、吳廣大澤鄉起事，天下響應','起因：戍卒失期當斬','史');}
 if(y<=208&&History.once('lisi')&&H.alt!=='fusu'){var l=P('lisi');if(l.alive)People.die('lisi','具五刑，腰斬咸陽');WS.log('李斯腰斬於咸陽','起因：趙高構陷','史');}
 if(y<=207&&History.once('qinFall')&&H.alt!=='fusu'){var z=P('zhaogao');if(z&&z.alive)People.die('zhaogao','為子嬰所殺');WS.log('趙高被誅；子嬰降，秦亡','起因：天下大亂','史');}};
History.shaqiu=function(saved){var H=S.hist;if(saved==='zheng'){H.zdie=(H.zdie||210)-4;H.alt='zheng';WS.log('始皇巡遊途中病重，得醫者救治轉危為安','起因：你在病榻前的處置','你所為');return;}
 People.die('yingzheng','東巡途中崩於沙丘');if(saved==='fusu'){H.alt='fusu';WS.log('始皇崩於沙丘；長公子扶蘇得遺詔即位','起因：你及時揭破矯詔','你所為');}else{var f=P('fusu');if(f.alive)People.die('fusu','奉矯詔自盡於上郡');var m=P('mengtian');if(m.alive)People.die('mengtian','被逼吞藥自盡');WS.log('始皇崩於沙丘；趙高、李斯矯詔，扶蘇、蒙恬被賜死，胡亥即位','起因：沙丘之謀','史');}};
History.hint=function(){var y=Eng.yb();if(y>233&&y<=235)return '聽說韓國有個口吃的公子，文章寫得秦王都讚嘆。';if(y>227&&y<=229)return '燕國那邊，有個劍客在易水邊喝得爛醉……';if(y>213&&y<=215)return '朝中有人上書，說私學亂政、應當燒書。';if(y>210&&y<=212)return '陛下身子大不如前，卻又要東巡了。';return '';};
NODES.histHanfei=function(){return Eng.L(['你聽說韓非被下了雲陽獄，李斯派人送去了毒藥。'],'hanfei',S.place,[ch('託人向秦王求情（需秦王信任）','hfDo',{k:'plead'}),ch('買通獄卒，送解毒湯進去','hfDo',{k:'antid'}),ch('……無能為力','hfDo',{k:'none'})]);};
NODES.hfDo=function(a){var ok=false,L=[];if(a.k==='plead'){var y=P('yingzheng');ok=y.alive&&y.trust>=40;L.push(ok?'秦王沉默良久：「……放他出來。」':'秦王冷冷地看了你一眼，沒有回答。');}else if(a.k==='antid'){ok=Inv.has('antidote')&&S.gold>=30;if(ok){Inv.add('antidote',-1);Inv.gold(-30);}L.push(ok?'你把解毒湯藏在食盒裡送了進去。韓非喝下毒藥後吐了一夜——活了下來。':'你沒有解毒湯，或錢不夠打點。');}
 if(ok){S.hist.hanfeiSaved=1;S.hist.done.hanfeiDie=S.day;P('hanfei').jailed=0;People.rel('hanfei',{aff:15,trust:15},pc().n+'救了我的命');WS.log('韓非死裡逃生','起因：'+pc().n+'相救','你所為');}else{S.hist.done.hanfeiDie=S.day;People.die('hanfei','雲陽獄中飲毒');WS.log('韓非死於雲陽獄','起因：李斯進讒','史');}return Eng.L(L,'hanfei',S.place,[ch('繼續','place')]);};
NODES.histJingke=function(){var j=P('jingke');j.here={d:S.day,per:S.per,pl:S.place};Eng.keep('jingke');return Eng.L([['jingke','「明日我要隨燕使入宮了。」他把劍擦得雪亮，笑得很輕，「你知道我要去做什麼。」']],'jingke',S.place,[ch('「別去。留下來。」','jkDo',{k:'stay'}),ch('「那我替你備好傷藥。」','jkDo',{k:'help'}),ch('默默看著他','jkDo',{k:'none'})]);};
NODES.jkDo=function(a){var j=P('jingke');if(a.k==='stay'&&(j.love>=40||j.aff>=60)){WS.log('燕使入秦獻圖，刺客臨陣不見蹤影','起因：荊軻為一人留下','你所為');S.hist.jingkeStay=1;People.rel('jingke',{love:6});return Eng.L([['jingke','「……好。易水我不去了。」']],'jingke',S.place,[ch('繼續','place')]);}
 People.die('jingke','刺秦不成，死於咸陽宮');WS.log('荊軻於咸陽宮行刺秦王，未成被誅','起因：燕太子丹所遣','史');return Eng.L([a.k==='stay'?'他搖搖頭，轉身走進了夜色。':'第二天，咸陽宮傳出了消息。'],'',S.place,[ch('繼續','place')]);};
NODES.histBurn=function(){return Eng.L(['官差挨家挨戶搜書。私藏者黥為城旦。'+(Inv.has('notes')?'師父的手札就在你的藥箱底層。':'')],'',S.place,[ch('把醫書藏進牆裡（醫藥書本不在燒列，但難保差役不識）','burnDo',{k:'hide'}),ch('交出去','burnDo',{k:'give'})]);};
NODES.burnDo=function(a){if(a.k==='give'){['notes','lawbook','bamboo'].forEach(function(k){if(S.inv[k])delete S.inv[k];});return Eng.L(['火光沖天。你看著竹簡一卷卷化成灰。'],'',S.place,[ch('繼續','place')]);}if(rand()<0.2){S.flags.held=S.day;['lawbook','bamboo'].forEach(function(k){delete S.inv[k];});return Eng.L(['差役敲開了牆——你被帶走了。'],'',S.place,[ch('……','held')]);}S.fam.book=1;return Eng.L(['差役在屋裡翻了一圈，沒發現牆裡的東西。家傳的醫書保住了。'],'',S.place,[ch('繼續','place')]);};
NODES.histShaqiu=function(){return Eng.L(['始皇東巡，病倒在沙丘。你'+(pc().medoff>=3?'作為侍醫隨行':'託扶蘇的關係趕到')+'——帳外，趙高與李斯在低聲密議。'],'yingzheng',S.place,[ch('全力救治陛下','sqDo',{k:'zheng'}),ch('揭破矯詔，急信上郡扶蘇','sqDo',{k:'fusu'}),ch('不敢捲入','sqDo',{k:'none'})]);};
NODES.sqDo=function(a){var me=pc();var ok=a.k==='zheng'?me.sk.med+rnd(30)>85:(a.k==='fusu'?(P('fusu').trust>=40||P('mengtian').trust>=40)&&rand()<0.7:false);History.shaqiu(ok?a.k:false);return Eng.L([ok?(a.k==='zheng'?'你在病榻前守了三天三夜，陛下的燒退了。':'你的信送到了上郡。扶蘇沒有自盡——他帶著蒙恬的大軍回到了咸陽。'):'歷史的車輪碾了過去。'],'',S.place,[ch('繼續','place')]);};
/* ===== NPC 自主：暗中鍾情、主動來訪 ===== */
var Npc={tick:function(){if(S.region==='road')return;for(var id in S.ppl){var p=S.ppl[id];if(!p.alive||!p.met||p.hh||id===S.pc)continue;if(p.aff>=40&&ageOf(p)>=16&&ageOf(pc())>=16&&p.spouse===''&&(p.g!==pc().g||S.world!=='male'&&rand()<0.3)&&rand()<0.08)p.love=clamp((p.love||0)+1,0,100);}
 if(S.queue.length)return;var c=Object.keys(S.ppl).filter(function(id){var p=S.ppl[id];return p.alive&&p.met&&!p.hh&&id!==S.pc&&!p.jailed&&!p.away&&p.loc&&p.loc.r===S.region&&(p.aff>=35||p.love>=50)&&Pace.allow(id,'visit');});if(c.length&&rand()<0.35)S.queue.push({go:'visit',a:{id:pick(c)}});}};
/* ===== 每日／每年鉤子 ===== */
Eng.on('day',function(){var me=pc();if(!me)return;
 if(me.alive&&S.region!=='held'){var hung=Eng.house().filter(function(p){return p.food<=8;});if(hung.length&&S.region!=='road'&&S.gold>=8){var nb=Math.min(Math.ceil(hung.length*1.5),Math.floor(S.gold/6));if(!Eng.foodKeys().length&&nb>0){S.gold-=nb*6;Inv.add('grain',nb);addLog('〔家〕餓得發慌，花'+nb*6+'兩買了粟米','家');}Eng.meal(true);}
  else if(hung.length&&S.region!=='road'&&!Eng.foodKeys().length&&S.gold<8&&(S.day-(S.flags.alms||-9))>=3){S.flags.alms=S.day;Inv.add('grain',Math.min(2,hung.length));me.mood=clamp(me.mood-6,0,100);S.fam.fame=Math.max(0,S.fam.fame-1);addLog('〔家〕囊中無錢，厚著臉皮向鄰里討了些粟米（每三日一次）','家');Eng.meal(true);}
 if(hung.length&&!Eng.foodKeys().length&&S.gold<8&&S.day-(S.flags.hungry||-9)>=2){S.flags.hungry=S.day;S.queue.push({go:'hungry',a:{},stop:1});}
  if(S.flags.debt&&S.gold>=S.flags.debt+40){Inv.gold(-S.flags.debt);addLog('〔家〕還清鄰里借糧 '+S.flags.debt+' 兩','家');S.flags.debt=0;}
  if(me.hp<25&&me.hp>0&&S.day-(S.flags.collapse||-99)>=8){S.flags.collapse=S.day;S.queue.push({go:'collapse',a:{},stop:1});}}
 Eng.house().forEach(function(p){if(p.preg&&S.day>=p.preg.due){var ks=People.birth(p);S.queue.push({go:'birth',a:{ids:ks.map(function(k){return k.id;}),mo:p.id},stop:1});}});
 if(me.spouse&&alive(me.spouse))People.tryConceive();
 var earners=Eng.house().filter(function(p){var a=ageOf(p);return p.id!==S.pc&&a>=16&&a<62&&p.hp>40&&!Ill.has(p,'old');});if(earners.length&&S.region!=='road')S.gold+=earners.length*(S.region==='frontier'?2:3);
 FW.tick();WS.tick();Gender.tick();if(S.region!=='road'&&ageOf(me)>=14){Pace.maybeIntro();Letters.tick();Npc.tick();}History.tick();
 S.invites=S.invites.filter(function(v){return v.day>=S.day;});S.calls=S.calls.filter(function(v){return v.until>=S.day;});
 if(!Eng.skipping&&rand()<0.25)Ev.roll('morning');});
Eng.on('year',function(){People.yearTick();Eng.house().forEach(function(p){if(p.id===S.pc)return;var a=ageOf(p);if(a<16&&a>=6){if(p.school)p.sk.lit=clamp(p.sk.lit+5,0,100);if(p.teach)p.sk[p.teach]=clamp(p.sk[p.teach]+5+(p.tal[p.teach]?3:0),0,100);if(!p.school&&!p.teach)p.sk.farm=clamp(p.sk.farm+2,0,100);}});
 Eng.house().forEach(function(p){if(p.school&&S.gold>=20)S.gold-=20;});});
NODES.eduPick=function(){var ks=Eng.house().filter(function(p){return p.id!==S.pc&&ageOf(p)>=6&&ageOf(p)<16;});if(!ks.length)return Eng.L(['家裡沒有適齡（六到十五歲）的孩子。'],'',S.place,[ch('↩','place')]);return Eng.L(['送誰去讀書？（學費每年二十兩）'],'',S.place,ks.map(function(k){return ch(k.n+(k.school?'（已在學）':''),'edu',{id:k.id,k:'school'});}).concat([ch('↩','place')]));};
NODES.edu=function(a){var p=P(a.id);if(a.k==='school'&&!p.school&&!Rule.ok(p,'school'))return Eng.L(['學室的先生搖頭：「'+Rule.why(p,'school')+'」','（只能在家自己教了。）'],'',S.place,[ch('↩','eduPick')]);if(a.k==='school'){p.school=p.school?0:1;}else{p.teach=a.k;}return Eng.L([p.n+(a.k==='school'?(p.school?'背起書箱去了學室。':'不再去學室了。'):'從今往後跟著學'+({med:'醫',mart:'武',farm:'農',trade:'商',craft:'手藝'}[a.k])+'。')],'',S.place,[ch('↩','place')]);};

/* ---------- 生存安全網：斷糧、病倒 ---------- */
NODES.hungry=function(){var hung=Eng.house().filter(function(p){return p.food<=8;});var L=['米缸見了底。'+hung.map(function(p){return p.id===S.pc?'你':p.n;}).join('、')+'餓得頭暈眼花。'];var c=[];
 c.push(ch('🙏 放下臉面去乞討','hgDo',{k:'beg'}));if(S.region!=='road')c.push(ch('🤝 向鄰里借糧（欠下人情）','hgDo',{k:'borrow'}));var it=Object.keys(S.inv).filter(function(k){return S.inv[k]>0&&ITEMS[k]&&ITEMS[k].p>=8&&ITEMS[k].k!=='book';})[0];if(it)c.push(ch('📦 典當'+ITEMS[it].n,'hgDo',{k:'pawn',it:it}));c.push(ch('🌿 去野外找吃的','forage'));
 return Eng.L(L,'',S.place,c);};
NODES.hgDo=function(a){var me=pc();var L=[];if(a.k==='beg'){Eng.pass(2);var n=1+rnd(2);Inv.add('grain',n);me.mood=clamp(me.mood-8,0,100);S.fam.fame=Math.max(0,S.fam.fame-1);L.push('你在街口站了半日，討到'+n+'升粟米。有人丟下一句「年紀輕輕的」，你只當沒聽見。');}
 else if(a.k==='borrow'){Eng.pass(1);Inv.add('grain',3);S.flags.debt=(S.flags.debt||0)+20;L.push('隔壁的大娘嘆口氣，舀了三升米給你：「先吃著，秋後再還。」（欠糧：約 20 兩）');}
 else if(a.k==='pawn'){var it=ITEMS[a.it];Inv.add(a.it,-1);var g=Math.max(4,Math.round(it.p*0.5));Inv.gold(g);L.push('當舖掌櫃撥了撥算盤，'+it.n+'換了'+g+'兩。');}
 return Eng.L(L,'',S.place,[ch('🍚 用膳','eat'),ch('↩ 行動選單','place')]);};
NODES.collapse=function(){var me=pc();var hh=Eng.house().filter(function(p){return p.id!==S.pc&&ageOf(p)>=12;});var who=hh[0]||P(Object.keys(S.ppl).filter(function(id){var q=S.ppl[id];return id!==S.pc&&q.alive&&q.met&&q.aff>=30&&!q.hh;}).sort(function(a,b){return P(b).aff-P(a).aff;})[0]);
 Eng.pass(4);me.hp=clamp(me.hp+30,0,100);me.sta=clamp(me.sta+60,0,100);me.food=clamp(me.food+35,0,100);var fee=Math.min(S.gold,8);Inv.gold(-fee);
 var L=['你眼前一黑，倒了下去。'];if(who){L.push('醒來時，'+(who.hh?who.n:who.n+'坐在床邊')+'正替你換額上的濕布。');if(!who.hh)People.rel(who.id,{aff:3,trust:3},'照顧病倒的'+me.n);L.push([who.id,who.hh?'「你再這樣不要命，這個家怎麼辦？」':'「醫者不自醫——你也太不愛惜自己了。」']);}else L.push('好心的店家把你扶進屋裡，灌了一碗熱粥。');
 L.push('（昏睡了大半日。健康+30、體力+60'+(fee?'；花去藥錢'+fee+'兩':'')+'。再這樣下去，可就不是昏倒那麼簡單了。）');return Eng.L(L,who?who.id:'',S.place,[ch('↩ 行動選單','place')]);};
