/* ===== 面板：開局設定、行囊、買賣、家族（族譜）、人脈（心態卡／記憶／書信）、結局冊、選單與設定 ===== */
var Sh={tab:''};
Sh.open=function(title,tabs,render,tab){$('sheet').className='sheet on';$('shT').textContent=title;Sh.render=render;Sh.tabs=tabs||[];Sh.tab=tab||(tabs&&tabs[0]?tabs[0][0]:'');Sh.draw();};
Sh.draw=function(){var t=$('shTabs');t.innerHTML=Sh.tabs.map(function(x){return '<button data-tab="'+x[0]+'" class="'+(x[0]===Sh.tab||Sh.tab.indexOf(x[0]+':')===0?'on':'')+'">'+x[1]+'</button>';}).join('');var y=$('shB').scrollTop;$('shB').innerHTML=Sh.render(Sh.tab)||'';$('shB').scrollTop=Sh.keep?y:0;Sh.keep=0;};
Sh.redraw=function(){Sh.keep=1;Sh.draw();};
Sh.close=function(){$('sheet').className='sheet';Sh.render=null;if(S){UI.hud();UI.badge();if(UI.cur==='map')UI.showMap();else if(UI.cur==='game'&&UI.sc&&!UI.busyOn&&!$('choices').children.length&&UI.li>=UI.sc.lines.length-1&&$('med').className.indexOf('on')<0)UI.choices(UI.sc.ch&&UI.sc.ch.length?UI.sc.ch:[ch('↩ 返回','place')]);}};
function bar(n,v,cl,max){max=max||100;return '<span>'+n+'</span><div class="bar '+(cl||'')+'"><i style="width:'+clamp(v/max*100,0,100)+'%"></i></div><span>'+Math.round(v)+'</span>';}
function seg(key,opts){return '<div class="seg">'+opts.map(function(o){return '<button data-set="'+key+'" data-v="'+o[0]+'" class="'+(String(SET[key])===String(o[0])?'on':'')+'">'+o[1]+'</button>';}).join('')+'</div>';}
var Panels={act:{}};
/* ---------- 開局設定 ---------- */
Panels.su=null;
Panels.setup=function(){Panels.su={mode:'std',world:'equal',g:'f',era:'y10',name:DEF_NAMES[0],r:rollBirth({g:'f'}),baby:false,birth:'',ctext:'',parsed:null};Sh.open('新的一生',[],Panels.suRender);};
Panels.suRender=function(){var u=Panels.su;var h='<h4>開局方式</h4><div class="seg">'+[['std','標準開局'],['rand','全隨機'],['custom','自設身世']].map(function(o){return '<button data-act="suMode" data-v="'+o[0]+'" class="'+(u.mode===o[0]?'on':'')+'">'+o[1]+'</button>';}).join('')+'</div>';
 h+='<h4>世界設定</h4><div class="seg">'+Object.keys(WORLDS).map(function(k){return '<button data-act="suWorld" data-v="'+k+'" class="'+(u.world===k?'on':'')+'">'+WORLDS[k].n+'</button>';}).join('')+'</div><p class="note">'+esc(WORLDS[u.world].d)+'</p>';
 h+='<h4>開局時間</h4><div class="seg">'+Object.keys(ERAS).map(function(k){return '<button data-act="suEra" data-v="'+k+'" class="'+(u.era===k?'on':'')+'">'+ERAS[k].n+'</button>';}).join('')+'</div><p class="note">'+esc(ERAS[u.era].d)+'</p>';
 h+='<h4>主角性別</h4><div class="seg">'+[['f','女'],['m','男']].map(function(o){return '<button data-act="suG" data-v="'+o[0]+'" class="'+(u.g===o[0]?'on':'')+'">'+o[1]+'</button>';}).join('')+'</div>'+(u.g==='f'?'<div class="row"><button class="btn'+(u.disg?' on':'')+'" data-act="suDisg">'+(u.disg?'☑':'☐')+' 女扮男裝開局</button></div>':'')+'<p class="note">'+(u.g==='m'?'男主角：稱呼、婚嫁（娶／入贅按世界設定）、心動角色反應、易裝（男扮女裝）都會跟著變；七位核心人物照樣可以結緣。':'女主角（標準開局預設）。')+'</p>';
 if(u.mode==='std'){h+='<h4>'+(u.g==='m'?'西醫':'女西醫')+'</h4><p class="note">'+(u.g==='m'?'他':'她')+'在隱世山谷隨師父青囊子學了十二年西方醫術——解剖、縫合、消毒、退燒、接骨、藥理、聽診——今日學成下山，來到咸陽。</p><label class="field">姓名（2–4 字）<input id="suName" maxlength="6" value="'+esc(u.name)+'" autocomplete="off"></label><div class="row">'+(u.g==='m'?DEF_NAMES_M:DEF_NAMES).map(function(n){return '<button class="btn" data-act="suNm" data-v="'+esc(n)+'">'+esc(n)+'</button>';}).join('')+'</div>';}
 else if(u.mode==='rand'){var r=u.r;var B=BIRTHS.filter(function(b){return b.k===r.birth;})[0];h+='<h4>隨機身世</h4><div class="rcard"><div class="rav">'+ART.sil({id:'pv',n:r.sur+r.gn,gn:r.gn,g:r.g,born:S?0:0,look:{hair:'#2a2020'},kind:'pc',alive:1,_age:r.age})+'</div><div><b>'+esc(r.sur+r.gn)+'</b>（'+(r.g==='f'?'女':'男')+'，'+(r.baby?'初生嬰兒':r.age+'歲')+'）<br>'+esc(B.n)+'——'+esc(B.d)+'<br>天賦：'+r.tal.map(function(t){return {med:'醫',mart:'武',lit:'文',trade:'商',farm:'農',craft:'工'}[t];}).join('、')+'；體'+r.at.con+' 智'+r.at.wit+' 貌'+r.at.look+'<br>'+(r.genes.length?'隱約有「'+r.genes.map(function(g){return GENES[g].n;}).join('、')+'」之相':'未見特殊稟賦')+(r.birth==='exile'?'<br>罪名：'+esc(r.crime)+'；流放'+esc(EXILE_DEST.filter(function(d){return d.k===r.dest;})[0].n):'')+'<br>兄弟姊妹 '+r.sibs+' 人'+(r.grand?'、祖母同住':'')+'</div></div>';
  h+='<div class="row"><button class="btn pri" data-act="suRoll">🎲 重抽</button><button class="btn'+(u.baby?' on':'')+'" data-act="suBaby">'+(u.baby?'☑':'☐')+' 從嬰兒開始</button></div><label class="field">指定出身<select id="suBirth"><option value="">隨機</option>'+BIRTHS.map(function(b){return '<option value="'+b.k+'"'+(u.birth===b.k?' selected':'')+'>'+b.n+'</option>';}).join('')+'</select></label><p class="note">流放之家：要護著家人走完流放路、在邊地開荒搭屋，或許還會在深山遇見傳授西醫的奇人。</p>';}
 else{h+='<label class="field">姓名（2–4 字，留空隨機）<input id="suName" maxlength="6" value="'+esc(u.cname||'')+'" autocomplete="off"></label><h4>自設身世（M14）</h4><label class="field">寫下你的身世（可含出身、年齡、秘密、仇人、舊毒、志向、專長、易裝…）<textarea id="suText" rows="5" maxlength="400" placeholder="例：我是罪臣之女，十七歲，女扮男裝；親生父親其實是李斯；身中寒毒；仇人是趙高；立志為家族翻案；擅長醫術。">'+esc(u.ctext)+'</textarea></label><div class="row"><button class="btn" data-act="suParse">🔍 解析預覽</button>'+(AI.ready()&&!AI.manual()?'<button class="btn" data-act="suRefine">✨ AI 精修解析</button>':'')+'</div>';
  if(u.parsed)h+='<div class="kv" id="suPrev"><b>解析結果'+(u.parsed.ai?'（AI 精修）':'（離線）')+'</b>'+(u.parsed.g&&u.parsed.g!==u.g?'<p class="note">⚠ 身世寫的是'+(u.parsed.g==='m'?'男':'女')+'，開局頁選了'+(u.g==='m'?'男':'女')+'——以開局頁為準。</p>':'')+(u.parsed.base==='std'?'<p class="note">以「下山的西醫」為底（保留標準開局的醫術、器具、師父）。</p>':'')+'<div class="mem">'+esc(Origin.preview(u.parsed)).replace(/\n/g,'<br>')+'</div></div>';}
 h+='<div class="row" style="margin-top:14px"><button class="btn pri big" data-act="suGo">踏入此生</button></div>';return h;};
Panels.act.suMode=function(v){Panels.su.mode=v;Sh.draw();};Panels.act.suWorld=function(v){Panels.su.world=v;Sh.redraw();};
Panels.act.suG=function(v){var u=Panels.su;if(u.g===v)return;u.g=v;var A=v==='m'?DEF_NAMES_M:DEF_NAMES,B=v==='m'?DEF_NAMES:DEF_NAMES_M;var i=B.indexOf(u.name);if(i>=0||!u.name)u.name=A[Math.max(0,i)];u.r=rollBirth({birth:u.r.birth,g:v,baby:u.baby});Sh.redraw();};
Panels.act.antiTake=function(){if(Fate.take())Sh.redraw();};
Panels.act.suDisg=function(){Panels.su.disg=!Panels.su.disg;Sh.redraw();};
Panels.act.suEra=function(v){Panels.su.era=v;Sh.redraw();};
Panels.act.suNm=function(v){Panels.su.name=v;Sh.redraw();};
Panels.act.suRoll=function(){var u=Panels.su;var b=$('suBirth');if(b)u.birth=b.value;u.r=rollBirth({birth:u.birth||'',baby:u.baby,g:u.g});Sh.redraw();};
Panels.act.suBaby=function(){var u=Panels.su;u.baby=!u.baby;u.r=rollBirth({birth:u.r.birth,g:u.g,baby:u.baby});Sh.redraw();};
Panels.act.suParse=function(){var u=Panels.su;u.ctext=$('suText').value;u.cname=($('suName')||{}).value||'';u.parsed=Origin.parse(u.ctext);Sh.redraw();};
Panels.act.suRefine=function(){var u=Panels.su;u.ctext=$('suText').value;UI.busy(true,'解析身世中…');Origin.refine(u.ctext).then(function(o){UI.busy(false);u.parsed=o;Sh.redraw();},function(e){UI.busy(false);toast('AI 解析失敗，改用離線解析');u.parsed=Origin.parse(u.ctext);Sh.redraw();});};
Panels.act.suGo=function(){var u=Panels.su;var first;START_BC=(ERAS[u.era]||ERAS.y10).bc;
 if(u.mode==='std'){var nm=(($('suName')||{}).value||u.name).replace(/\s/g,'').slice(0,6)||DEF_NAMES[0];first=Start.std({name:nm,world:u.world,g:u.g});}
 else if(u.mode==='rand'){first=Start.rand(u.r,{world:u.world});}
 else{u.ctext=($('suText')||{}).value||u.ctext;if(!u.parsed||u.parsed.raw!==u.ctext.trim().slice(0,400))u.parsed=Origin.parse(u.ctext);var o=u.parsed;var cn0=(($('suName')||{}).value||'').replace(/\s/g,'').slice(0,6);if(o.base==='std'){first=Start.std({name:cn0||(u.g==='m'?DEF_NAMES_M:DEF_NAMES)[0],world:u.world,g:u.g,age:o.age!=null&&o.age>=14?o.age:19});Origin.apply(o);}else{var r=rollBirth({birth:o.birth||'',g:u.g,baby:false});if(o.age!=null&&o.age>=14)r.age=o.age;if(cn0.length>=2){r.sur=cn0.slice(0,1);r.gn=cn0.slice(1);}first=Start.rand(r,{world:u.world,origin:o});}}
 if(u.disg&&u.g==='f'&&pc().g==='f'&&!Gender.on()){Gender.start('m');(S.origin=S.origin||{lines:[]}).lines=(S.origin.lines||[]);S.origin.lines.push('出門前，你束起長髮、纏好束胸，換上一身男裝。從今往後，不知情的人會叫你「公子」——直到有人識破。');}
 UI.begin(first);};
/* ---------- 行囊 ---------- */
Panels.bag=function(tab){Sh.open('行囊',[['st','狀態'],['inv','物品'],['craft','製藥'],['tech','醫術']],Panels.bagR,tab||'st');};
Panels.bagR=function(tab){var me=pc();
 if(tab==='inv'){var cats={food:'食物',med:'藥物',mat:'材料',tool:'器具',wear:'衣物',gift:'禮物',book:'書冊'};var by={};Object.keys(S.inv).forEach(function(k){var it=ITEMS[k];if(!it||!S.inv[k])return;var key=it.k+'|'+it.n;if(!by[key])by[key]={n:it.n,c:it.k,q:0,k:k,d:it.d||''};by[key].q+=S.inv[k];});
  var h='';Object.keys(cats).forEach(function(c){var L=Object.keys(by).filter(function(x){return by[x].c===c;}).map(function(x){return by[x];});if(!L.length)return;h+='<h4>'+cats[c]+'</h4>';L.forEach(function(i){var use=c==='food'?'<button class="btn" data-act="eatOne" data-v="'+i.k+'">吃</button>':(i.k==='dose'?'<button class="btn" data-act="dose">服</button>':(i.k==='anti'?'<button class="btn" data-act="antiTake">服</button>':''));h+='<div class="item"><b>'+esc(i.n)+'</b>×'+i.q+'<small>'+esc(i.d)+'</small>'+use+'</div>';});});
  return (h||'<p class="note">行囊空空。</p>')+'<p class="note">野外採來的東西，認不準的就混在一起——吃之前多想想。</p>';}
 if(tab==='craft'){return RECIPES.map(function(r,i){var e=Craft.can(r);return '<div class="item"><b>'+esc(r.n)+'</b>×'+r.out+'<small>'+esc(r.d)+'｜需：'+Object.keys(r.need).map(function(k){return ITEMS[k].n+r.need[k]+'（'+(S.inv[k]||0)+'）';}).join('、')+(r.tool?'；器具：'+ITEMS[r.tool].n:'')+'</small><button class="btn'+(e?' dis':' pri')+'" data-act="craft" data-v="'+i+'">'+(e?esc(e):'製作')+'</button></div>';}).join('')+'<p class="note">製作耗一個時辰。酒精要先有陶甑蒸餾器（市集有賣，或向師父求）。</p>';}
 if(tab==='tech'){return '<div class="tlist">'+TECH_ORDER.map(function(t){var k=S.fam.tech[t];return '<div class="item'+(k?'':' lock')+'"><b>'+TECHS[t].n+'</b><small>'+esc(TECHS[t].d)+(t==='incant'||t==='bleed'?'（古法，有害）':'')+'</small>'+(k?'✔':(t==='incant'||t==='bleed'||t==='herbs'?'':'未習'))+'</div>';}).join('')+'</div><p class="note">醫術 '+me.sk.med+'。新技法可在醫館「研習醫術」或向師父學。家傳醫術會隨家業傳給繼承人。</p>'+(S.afl&&!S.afl.cured?'<div class="row"><button class="btn" data-act="aflRes">🧪 研究體內舊毒解法（'+S.afl.cure+'%）</button></div>':'');}
 var ex=me.expr.map(function(g){return '<span class="tag">'+GENES[g].n+'</span>';}).join('');
 return '<div class="pat"><div class="pav">'+ART.avatar(me)+'</div><div><b style="font-size:17px">'+esc(me.n)+'</b>（'+(me.g==='f'?'女':'男')+(Gender.on()?'，易作'+(S.disg.as==='m'?'男':'女')+'裝':'')+'，'+ageOf(me)+'歲）<div class="note">'+esc(me.title||JOBS[me.job]||'')+(me.office?'・'+OFFICE[me.office]:'')+(me.medoff?'・'+MEDOFF[me.medoff]:'')+(me.rank?'・爵 '+RANKS[me.rank]:'')+'｜'+esc(Fam.name())+'第'+S.fam.gen+'代</div></div></div>'
  +'<div class="bars">'+bar('飽食',me.food)+bar('體力',me.sta,'t')+bar('健康',me.hp,'h')+bar('心情',me.mood)+bar('腳',me.feet==null?100:me.feet,'t')+bar('衣物',me.cloth==null?100:me.cloth)+'</div>'
  +'<div class="pstat"><div>體溫<b>'+me.temp.toFixed(1)+'</b></div><div>體感<b>'+Math.round(Eng.effT(me))+'°</b></div><div>銀兩<b>'+S.gold+'</b></div><div>名聲<b>'+S.fam.fame+'</b></div><div>惡名<b>'+(S.fam.notor||0)+'</b></div><div>住所<b>'+Eng.HOUSE_N[S.fam.house||0]+'</b></div></div>'
  +'<div class="pstat"><div>醫<b>'+me.sk.med+'</b></div><div>農<b>'+me.sk.farm+'</b></div><div>工<b>'+me.sk.craft+'</b></div><div>商<b>'+me.sk.trade+'</b></div><div>武<b>'+me.sk.mart+'</b></div><div>文<b>'+me.sk.lit+'</b></div></div>'
  +'<div class="kv"><b>體質</b>體'+me.at.con+' 智'+me.at.wit+' 貌'+me.at.look+' 魅'+me.at.cha+' 巧'+me.at.dex+(ex?'<br>'+ex:'')+'</div><div class="kv"><b>病痛</b>'+esc(Ill.str(me))+(me.preg?'；有孕（約'+Math.max(0,me.preg.due-S.day)+'日後臨盆）':'')+(S.afl&&!S.afl.cured?'；舊毒「'+esc(S.afl.n)+'」（距上次服藥'+(S.day-S.afl.last)+'日）':'')+'</div>'
  +(S.idn.hist.length?'<div class="kv"><b>身分沿革</b>'+S.idn.hist.map(function(h){return esc(Idn.K[h.k]+'→'+h.to+(h.by?'（'+cn(h.by)+'）':''));}).join('；')+'</div>':'')
  +'<div class="kv"><b>天時</b>'+esc(Eng.dateStr()+'・'+PERIODS[S.per]+'・'+Weather.str()+'・'+WORLDS[S.world].n+'世界')+'</div>';};
Panels.act.eatOne=function(k){var it=ITEMS[k];if(!S.inv[k])return;Inv.add(k,-1);var me=pc();me.food=clamp(me.food+it.food,0,100);if(it.poison){Ill.add(me,'poison',it.poison+1);toast('🤢 不對勁……');}else toast('吃了'+it.n);UI.hud();Sh.redraw();};
Panels.act.dose=function(){if(Poison.dose())UI.hud();Sh.redraw();};
Panels.act.craft=function(i){var r=Craft.make(+i);toast((r.ok?'⚗ ':'✘ ')+r.msg,2600);UI.hud();Sh.redraw();if(S.queue.length){Sh.close();UI.go('place');}};
Panels.act.aflRes=function(){var t=Poison.research();Sh.close();UI.present(Eng.L([t],'',S.place,[ch('繼續','place')]));};
/* ---------- 買賣 ---------- */
Panels.price=function(k,sell){var p=ITEMS[k].p;var m=1;if(S.flags.dear&&S.day-S.flags.dear<30&&ITEMS[k].k==='food')m=1.5;if(S.flags.cheap&&S.day-S.flags.cheap<30&&ITEMS[k].k==='food')m=0.8;if(S.region==='frontier')m*=1.15;return Math.max(1,Math.round(sell?p*0.5:p*m));};
Panels.shop=function(a){Panels.shopList=SHOPS[S.place]||SHOPS.market;Sh.open('買賣・'+PLACES[S.place].n,[['buy','買'],['sell','賣']],Panels.shopR,a&&a.sell?'sell':'buy');};
Panels.shopR=function(tab){if(tab==='sell'){var by={};Object.keys(S.inv).forEach(function(k){var it=ITEMS[k];if(!it||!S.inv[k]||it.p<=0)return;if(!by[it.n])by[it.n]={k:k,q:0};by[it.n].q+=S.inv[k];});return '<p class="note">銀兩 '+S.gold+'</p>'+Object.keys(by).map(function(n){var x=by[n];return '<div class="item"><b>'+esc(n)+'</b>×'+x.q+'<button class="btn" data-act="sell" data-v="'+x.k+'">賣 '+Panels.price(x.k,1)+'</button></div>';}).join('');}
 return '<p class="note">銀兩 '+S.gold+(S.flags.dear&&S.day-S.flags.dear<30?'｜糧價騰貴':'')+'</p>'+Panels.shopList.map(function(k){var it=ITEMS[k];if(!it)return '';var pr=Panels.price(k);return '<div class="item"><b>'+esc(it.n)+'</b><small>'+esc(it.d||'')+(S.inv[k]?'（有'+S.inv[k]+'）':'')+'</small><button class="btn'+(S.gold>=pr?' pri':' dis')+'" data-act="buy" data-v="'+k+'">'+pr+' 兩</button></div>';}).join('');};
Panels.act.buy=function(k){var pr=Panels.price(k);if(S.gold<pr){toast('銀兩不足');return;}Inv.gold(-pr);Inv.add(k,1);if(k==='seed'&&!S.fam.land&&S.region==='xianyang')toast('（城郊田舍可買地：田地要另購）');Sh.redraw();UI.hud();};
Panels.act.sell=function(k){if(!S.inv[k])return;var pr=Panels.price(k,1);Inv.add(k,-1);Inv.gold(pr);Sh.redraw();UI.hud();};
/* ---------- 家族 ---------- */
Panels.fam=function(tab){Sh.open('家族・'+Fam.name(),[['mem','家人'],['tree','族譜'],['est','家業'],['gen','歷代']],Panels.famR,tab||'mem');};
Panels.famR=function(tab){var me=pc();
 if(tab==='tree')return Panels.tree();
 if(tab==='est'){var g=S.fam.grudge;return '<div class="pstat"><div>家族<b>'+TIERS[Fam.tier()].n+'</b></div><div>家業分<b>'+Fam.score()+'</b></div><div>名聲<b>'+S.fam.fame+'</b></div><div>銀兩<b>'+S.gold+'</b></div><div>住所<b>'+Eng.HOUSE_N[S.fam.house||0]+'</b></div><div>田<b>'+S.fam.plots.length+'</b></div></div>'
  +'<div class="kv"><b>等級</b>'+TIERS.map(function(t,i){return (i<=Fam.tier()?'◆':'◇')+t.n+'（'+t.v+'）';}).join(' → ')+'</div>'
  +'<div class="kv"><b>醫館</b>'+(S.fam.clinic.open?'已開（規模 '+S.fam.clinic.lv+(S.fam.clinic.rentFrom?'；租自'+cn(S.fam.clinic.rentFrom)+(S.fam.clinic.rentPrice?'・'+S.fam.clinic.rentPrice+'兩':''):'')+'）；學徒：'+(S.fam.clinic.apps.filter(alive).map(cn).join('、')||'無'):'未開')+'</div>'
  +'<div class="kv"><b>田地</b>'+(S.fam.plots.map(function(p,i){return '第'+(i+1)+'塊：'+Farm.st[p.st];}).join('；')||'無')+'</div>'
  +'<div class="kv"><b>商隊</b>'+((S.fam.biz||[]).filter(function(b){return !b.done;}).map(function(b){return b.amt+'兩（'+(b.back-S.day)+'日後）';}).join('、')||'無')+'</div>'
  +(g?'<div class="kv"><b>冤案</b>'+esc(g.crime)+'——'+(g.done?'已平反':'線索 '+g.ev+'/3：'+(g.clues.join('、')||'無'))+'</div>':'')
  +'<div class="kv"><b>家傳醫術</b>'+Object.keys(S.fam.tech).map(function(t){return TECHS[t]?TECHS[t].n:'';}).filter(Boolean).join('、')+(S.fam.book?'；家傳醫書':'')+'</div>';}
 if(tab==='gen'){var L=Meta.get().lives.slice().reverse();return '<h4>本家歷代</h4>'+(S.lives.map(function(l){var p=P(l.id);return p?'<div class="item"><b>第'+l.gen+'代 '+esc(p.n)+'</b><small>享年'+ageOf(p)+'・'+esc(p.cause||'')+'</small></div>':'';}).join('')||'<p class="note">你是第一代。</p>')+'<h4>所有存檔的人生</h4>'+(L.map(function(l){return '<div class="item"><b>'+esc(l.fam+'・第'+l.gen+'代 '+l.name)+'</b><small>'+l.age+'歲'+(l.title?'・'+esc(l.title):'')+'・醫'+l.med+'</small></div>';}).join('')||'<p class="note">尚無。</p>');}
 var ids=Object.keys(S.ppl).filter(function(id){var p=S.ppl[id];return id!==S.pc&&(p.hh||id===me.spouse||me.par.indexOf(id)>=0||p.par.indexOf(S.pc)>=0);});ids.sort(function(a,b){return (P(b).alive-P(a).alive)||(ageOf(P(b))-ageOf(P(a)));});
 return ids.map(function(id){var p=P(id);var a=ageOf(p);var kid=a>=6&&a<16&&p.alive&&p.hh;var here=People.present().indexOf(id)>=0;
  return '<div class="fcard'+(p.alive?'':' dead')+'"><div class="fav">'+ART.avatar(p)+'</div><div class="fi"><b>'+esc(p.n)+'</b> <small>'+esc(p.rel||People.relTo(id))+'・'+(p.g==='f'?'女':'男')+a+'歲'+(p.alive?'':'・已故（'+esc(p.cause||'')+'）')+'</small>'
   +(p.alive?'<div class="mini">'+bar('健',p.hp,'h')+bar('飽',p.food)+bar('心',p.mood)+'</div><div class="note">'+(p.ill.length?'🤒'+esc(Ill.str(p))+'　':'')+'心聲：'+esc(People.thought(p))+'</div><div class="note">醫'+p.sk.med+' 文'+p.sk.lit+' 農'+p.sk.farm+' 武'+p.sk.mart+(p.expr.length?'｜'+p.expr.map(function(g){return GENES[g].n;}).join('、'):'')+(p.school?'｜在學':'')+(p.teach?'｜學'+{med:'醫',mart:'武',farm:'農',trade:'商',craft:'工'}[p.teach]:'')+'</div>':'')
   +(p.alive?'<div class="row">'+(here?'<button class="btn" data-act="famTalk" data-v="'+id+'">交談</button>':'')+(p.ill.length&&(here||Eng.atHome())?'<button class="btn" data-act="famTreat" data-v="'+id+'">診治</button>':'')+(kid?['school','med','mart','farm','trade'].map(function(k){return '<button class="btn'+((k==='school'&&p.school)||p.teach===k?' on':'')+'" data-act="famEdu" data-v="'+id+'|'+k+'">'+{school:'入學',med:'教醫',mart:'習武',farm:'學農',trade:'學商'}[k]+'</button>';}).join(''):'')+'</div>':'')+'</div></div>';}).join('')||'<p class="note">孑然一身。</p>';};
Panels.tree=function(){var me=pc();var set={};function add(id,d){if(!id||set[id]!==undefined||!P(id))return;set[id]=1;var p=P(id);p.par.forEach(function(x){add(x,d);});p.kids.forEach(function(x){add(x,d);});if(p.spouse)set[p.spouse]=set[p.spouse]||1;}
 add(S.pc);S.lives.forEach(function(l){add(l.id);});var ids=Object.keys(set).filter(function(id){return P(id);});var gen={};function g(id,seen){if(gen[id]!=null)return gen[id];var p=P(id);var pp=p.par.filter(function(x){return set[x];});if(!pp.length){var sp=P(p.spouse);if(sp&&sp.par.some(function(x){return set[x];})&&!seen){gen[id]=g(sp.id,1);return gen[id];}gen[id]=0;return 0;}gen[id]=Math.max.apply(null,pp.map(function(x){return g(x);}))+1;return gen[id];}
 ids.forEach(function(id){g(id);});var rows={};ids.forEach(function(id){var k=gen[id];(rows[k]=rows[k]||[]).push(id);});var keys=Object.keys(rows).map(Number).sort(function(a,b){return a-b;});var done={};
 return '<div class="tree">'+keys.map(function(k){var r=rows[k];var cells=[];r.forEach(function(id){if(done[id])return;done[id]=1;var p=P(id);var sp=p.spouse&&rows[k].indexOf(p.spouse)>=0?P(p.spouse):null;if(sp)done[sp.id]=1;cells.push('<div class="tnode">'+Panels.chip(p)+(sp?'<span class="teq">＝</span>'+Panels.chip(sp):'')+'</div>');});return '<div class="trow"><em>'+cnum0(k+1)+'</em>'+cells.join('')+'</div>';}).join('<div class="tline"></div>')+'</div><p class="note">紅框＝現任家主；灰色＝已故。族譜隨婚嫁、生育、收養自動增長。</p>';};
Panels.chip=function(p){var yb=Eng.yb(p.born);return '<span class="tchip'+(p.id===S.pc?' cur':'')+(p.alive?'':' dead')+'"><i>'+ART.avatar(p)+'</i><b>'+esc(p.n)+'</b><small>'+(p.alive?ageOf(p)+'歲':'享年'+ageOf(p))+'</small></span>';};
Panels.act.famTalk=function(id){Sh.close();UI.go('talk',{id:id});};
Panels.act.famTreat=function(id){Sh.close();UI.go('treat',{id:id});};
Panels.act.famEdu=function(v){var a=v.split('|');var p=P(a[0]);if(a[1]==='school'&&!p.school&&!Rule.ok(p,'school')){toast(Rule.why(p,'school'),3000);return;}if(a[1]==='school'){p.school=p.school?0:1;if(p.school&&S.gold<20)toast('學費每年二十兩，記得備好');}else p.teach=p.teach===a[1]?'':a[1];if(a[1]==='med'&&pc().sk.med<30){toast('你的醫術不足以教人（需 30）');p.teach='';}Sh.redraw();};
/* ---------- 人脈 ---------- */
Panels.ppl=function(tab){Sh.open('人脈',[['rom','心動'],['list','相識'],['let','書信'],['sec','秘密'],['news','大事']],Panels.pplR,tab||'rom');};
Panels.pplR=function(tab){if(tab&&tab.indexOf('p:')===0)return Panels.pdet(tab.slice(2));if(tab&&tab.indexOf('l:')===0)return Panels.letter(+tab.slice(2));
 if(tab==='let'){if(!S.letters.length)return '<p class="note" style="text-align:center;margin-top:40px">尚無來信。熟絡的人會寄信、邀約、送禮，也可能有人暗中寫信給你。</p>';var h='';for(var i=S.letters.length-1;i>=0;i--){var l=S.letters[i];var anon=l.k==='crush'&&!l.rep;h+='<button class="env'+(l.read?' read':'')+'" data-act="letOpen" data-v="'+i+'"><span class="wax">'+(anon?'？':esc(cn(l.id).slice(0,1)))+'</span><span class="ef"><b>'+(anon?'無署名':esc(cn(l.id)))+'</b>　<small>'+'第'+l.d+'日'+'</small><p>'+esc(l.t.slice(0,24))+'…</p></span>'+(l.read?(l.rep?'<small>已回</small>':''):'<span class="dot"></span>')+'</button>';}return h;}
 if(tab==='sec'){var sec=FW.secretsOf();return (sec.length?sec.map(function(f){var kn=f.kn.filter(function(x){return x!==S.pc;});return '<div class="kv"><b>🔏 '+esc(f.t)+'</b>知情者：'+(kn.map(function(x){return esc(cn(x))+(f.seal[x]?'（託付守秘）':'');}).join('、')||'只有你自己')+(Object.keys(f.rum).length?'<br>聽到風聲：'+Object.keys(f.rum).map(function(x){return esc(cn(x));}).join('、'):'')+'</div>';}).join(''):'<p class="note">你沒有不可告人的秘密。</p>')+'<p class="note">親口告訴某人的秘密，對方會守口如瓶（除非反目、被審問）。秘密只會慢慢傳開（M13／M22）。</p>';}
 if(tab==='rom')return Panels.romR();
 if(tab==='news'){return '<h4>近期大事（M26）</h4><div class="mem">'+(WS.brief(12).map(esc).join('<br>')||'風平浪靜')+'</div><h4>耳聞</h4><div class="mem">'+esc(History.hint()||'——')+'</div>';}
 var ids=Object.keys(S.ppl).filter(function(id){var p=S.ppl[id];return id!==S.pc&&p.met&&!p.hh;}).sort(function(a,b){var x=P(a),y=P(b);return (y.alive-x.alive)||((y.aff+y.love)-(x.aff+x.love));});
 return '<div class="plist">'+ids.map(function(id){var p=P(id);var w=People.where(id);return '<button class="pcard'+(p.alive?'':' dead')+'" data-act="pOpen" data-v="'+id+'"><span class="fav">'+ART.avatar(p)+'</span><span class="pi"><b>'+esc(p.n)+'</b> <small>'+esc(p.title||JOBS[p.job]||'')+'・'+ageOf(p)+'歲'+(p.spouse===S.pc?'・配偶':(p.lover?'・心上人':''))+'</small><span class="hb">♥'+p.aff+' 信'+p.trust+' 情'+(p.love||0)+'</span><small>'+(p.alive?(w&&PLACES[w]?'📍'+PLACES[w].n:'不知去向'):'已故')+'</small></span></button>';}).join('')+'</div>'+(ids.length?'':'<p class="note">還沒有結識什麼人。</p>');};
Panels.romR=function(){var h='<p class="note">七段羈絆沒有固定路線：好感、信任、情意到了，相遇時便會翻開下一章。可以同時與幾個人相知，也可以誰都不選。</p><div class="plist">';
 Rom.CORE.forEach(function(id){var p=P(id);var N=NAMED[id];if(!p)return;var pr=Rom.progress(id);var met=p.met;var dots='';for(var i=0;i<pr.n;i++)dots+=i<pr.s?'●':'○';
  var at=[];N.at.forEach(function(x,k){if(x&&PLACES[x]&&at.indexOf(PLACES[x].n+'（'+PER_S[k]+'）')<0&&at.length<3)at.push(PLACES[x].n+'（'+PER_S[k]+'）');});
  var st=!p.alive?'已故':(p.spouse===S.pc?'💍 已成眷屬':(p.lover?'💗 互許心意':(pr.why===''?'💞 下一章「'+pr.next+'」已可觸發':(met?(pr.next?'下一章「'+pr.next+'」：'+pr.why:pr.why):'未相識'))));
  h+='<button class="pcard'+(p.alive?'':' dead')+'" data-act="'+(met?'pOpen':'noop')+'" data-v="'+id+'"><span class="fav">'+(met?ART.avatar(p):ART.sil({g:p.g,_age:ageOf(p),n:'？',alive:p.alive}))+'</span><span class="pi"><b>'+(met?esc(p.n):'？？？')+'</b> <small>'+esc((p.sub||N.sub))+'</small><span class="hb">'+dots+'　情'+(p.love||0)+' 好'+p.aff+' 信'+p.trust+'</span><small>'+esc(st)+'</small>'+(p.alive&&!p.hh?'<small>常在：'+esc(at.join('、')||'行蹤不定')+'</small>':'')+'</span></button>';});
 return h+'</div>';};
Panels.pdet=function(id){var p=P(id);var mem=Nom.list(id,14).slice().reverse();var kn=FW.knows(id).filter(function(f){return !f.pub;}).slice(-5);var ru=FW.rumors(id).slice(-3);
 return '<button class="btn" data-act="pBack">↩ 返回</button><div class="gdet" style="margin-top:8px"><div class="dtop">'+(ART.hasChar(p)?ART.html('char',p.portrait):'<div class="bigav">'+ART.avatar(p)+'</div>')+'<div class="dname">'+esc(p.n)+'<small>'+esc((p.title||JOBS[p.job]||'')+'・'+People.relTo(id))+'</small></div></div>'
  +'<div class="bars">'+bar('好感',p.aff+100,'',200)+bar('信任',p.trust+100,'t',200)+bar('情意',p.love||0)+bar('健康',p.hp,'h')+'</div>'
  +'<div class="kv"><b>性格</b>'+esc(p.pers.join('、'))+'｜喜好：'+(p.aff>=15?esc(p.like.join('、')):'？？？')+'</div>'
  +'<div class="kv"><b>心態卡（M20）</b>'+esc(Bond.card(id))+'</div>'
  +'<div class="kv"><b>約定</b><div class="mem">'+((typeof Deal!=='undefined'?Deal.forNpc(id):[]).map(function(d){return ({open:'⏳',done:'✅',broken:'✘'}[d.status]||'・')+' '+esc(Deal.str(d))+(d.status==='open'?'（未了）':d.status==='done'?'（已兌現）':'');}).join('<br>')||'尚無')+'</div></div>'
  +'<div class="kv"><b>記憶（M21）</b><div class="mem">'+(mem.map(function(m){return (m.k!=='n'?'◆':'・')+esc(m.t);}).join('<br>')||'尚無')+'</div></div>'
  +'<div class="kv"><b>所知（M13）</b><div class="mem">'+(kn.map(function(f){return '・'+esc(f.t);}).concat(ru.map(function(f){return '・（傳聞）'+esc(f.t);})).join('<br>')||'——')+'</div></div>'
  +(p.kind==='named'?'<div class="kv"><b>簡介</b>'+esc((P(id).bio||NAMED[id].bio))+'</div>':'')+'</div>';};
Panels.letter=function(i){var l=S.letters[i];if(!l)return '';l.read=1;UI.badge();var parts=l.t.split('——');var h='<button class="btn" data-act="letBack">↩ 返回信匣</button><div class="jian">'+esc(parts[0])+(parts[1]?'<div class="from">——'+esc(parts[1])+'</div>':'')+'</div>';
 if(l.rep)h+='<p class="note" style="text-align:center">已回信：'+esc(l.rt||{warm:'溫柔',tease:'俏皮',polite:'得體',decline:'婉拒',free:''}[l.rep])+'</p>';
 else h+='<div class="reply"><button class="cbtn" data-act="rep" data-v="'+i+'|warm">💌 溫柔地回信'+(l.k==='invite'?'（赴約）':'')+'</button><button class="cbtn" data-act="rep" data-v="'+i+'|tease">😊 俏皮地回信</button><button class="cbtn" data-act="rep" data-v="'+i+'|polite">📜 得體地回信</button><button class="cbtn" data-act="rep" data-v="'+i+'|decline">🙅 婉拒</button><button class="cbtn ai" data-act="rep" data-v="'+i+'|free">✍️ 親筆回信</button></div>';
 if(l.k==='invite'&&l.o)h+='<p class="note">約在'+cnum0(Math.max(0,l.o.dd))+'日後'+PERIODS[l.o.per]+'，'+esc(PLACES[l.o.pl].n)+'。</p>';if(l.k==='ask')h+='<p class="note">去'+esc(cn(l.id))+'所在處交談，可替其家人出診。</p>';return h;};
Panels.act.noop=function(){toast('尚未相識——到他常出沒的地方碰碰運氣吧。',2200);};Panels.act.pOpen=function(id){Sh.tab='p:'+id;Sh.draw();};Panels.act.pBack=function(){Sh.tab='list';Sh.draw();};
Panels.act.letOpen=function(i){Sh.tab='l:'+i;Sh.draw();};Panels.act.letBack=function(){Sh.tab='let';Sh.draw();};
Panels.act.rep=function(v){var a=v.split('|');var i=+a[0];if(a[1]==='free'){Kb.ask('親筆回信給'+cn(S.letters[i].id),function(t){if(!t.trim())return;Letters.reply(i,'free',t.slice(0,80));toast('✉ 已寄出');Sh.draw();});return;}Letters.reply(i,a[1]);toast('✉ 已寄出回信');Sh.draw();};
/* ---------- 結局冊 ---------- */
Panels.album=function(){Sh.open('結局冊',[['ends','獨特結局'],['fixed','十二結局'],['lives','歷代人生']],Panels.albR);};
Panels.albR=function(tab){var g=Meta.get();if(tab&&tab.indexOf('e:')===0){var e=g.ends.filter(function(x){return x.id===tab.slice(2);})[0];return '<button class="btn" data-act="albBack">↩ 返回</button>'+(e?UI.endHtml(e):'');}
 if(tab==='fixed')return '<div class="fgrid">'+Object.keys(End.FIXED).map(function(k){var E=End.FIXED[k],on=g.fixed[k];return '<div class="fend'+(on?'':' lock')+'"><i>'+E.type+'</i><b>'+(on?esc(E.t):'？？？')+'</b><small>'+(on?esc(E.txt):'')+'</small></div>';}).join('')+'</div><p class="note">已解鎖 '+Object.keys(g.fixed).length+' / 12（跨存檔保留）。</p>';
 if(tab==='lives')return g.lives.slice().reverse().map(function(l){return '<div class="item"><b>'+esc(l.fam+'・第'+l.gen+'代 '+l.name)+'</b><small>'+l.age+'歲・醫'+l.med+'</small></div>';}).join('')||'<p class="note">尚無。</p>';
 return g.ends.length?g.ends.slice().reverse().map(function(e){return '<button class="eitem t'+({HE:'he',BE:'be',NE:'ne','隱藏':'hid'}[e.type]||'ne')+'" data-act="albOpen" data-v="'+e.id+'"><i>'+esc(e.type)+'</i><b>'+esc(e.title)+'</b><small>'+esc((e.name||'')+'・'+(e.kn||'')+'・'+(e.source==='ai'?'AI':'離線'))+'</small></button>';}).join('')+'<p class="note">共 '+g.ends.length+' 個結局（跨存檔永久收藏）。</p>':'<p class="note" style="text-align:center;margin-top:40px">尚未收藏結局。告白、成婚、辭世、傳代斷絕或主動「結束這一生」時，都會寫下一個獨一無二的結局。</p>';};
Panels.act.albOpen=function(id){Sh.tab='e:'+id;Sh.draw();};Panels.act.albBack=function(){Sh.tab='ends';Sh.draw();};
/* ---------- 選單／設定 ---------- */
var MenuUI={};
MenuUI.open=function(tab){Sh.open('選單',[['main','總覽'],['save','存檔'],['load','讀檔'],['set','設定'],['log','回顧'],['full','完整日誌']],MenuUI.render,tab);};
MenuUI.render=function(tab){if(tab==='save'||tab==='load')return MenuUI.slots(tab);if(tab==='set')return MenuUI.settings();if(tab==='log')return MenuUI.log();if(tab==='full')return MenuUI.full();
 return '<div class="mgrid"><button class="mbtn" data-m="save"><i>💾</i>存檔</button><button class="mbtn" data-m="load"><i>📂</i>讀檔</button><button class="mbtn" data-m="set"><i>⚙</i>設定</button><button class="mbtn" data-m="log"><i>📜</i>回顧</button><button class="mbtn" data-m="alb"><i>📖</i>結局冊</button><button class="mbtn" data-m="title"><i>🏮</i>標題</button></div>'
  +(S?'<div class="kv"><b>本生</b>'+esc(pc().n+'・'+Fam.name()+'第'+S.fam.gen+'代・'+Eng.dateStr())+'；看診'+S.stats.pat+'、治癒'+S.stats.cure+'</div><div class="row"><button class="btn" data-act="endLife">🕯 結束這一生</button></div>':'')
  +'<p class="note">AI：'+(SET.ai?(AI.ready()?'已啟用（'+(SET.aiSrc==='manual'?'手動貼上':(PRESETS[SET.preset]||{}).n||SET.preset)+(SET.preset==='deepseek'&&SET.model?' · '+SET.model:'')+'）':'已啟用但暫停／未設定 Key → 離線劇情'+(AI.lastErr?'｜'+esc(AI.lastErr):'')):'離線模式（事件庫）')+'</p>';};
MenuUI.slots=function(mode){var h='';['auto',1,2,3].forEach(function(s){var i=slotInfo(s);if(mode==='save'&&s==='auto')return;
 h+='<div class="slot"><div class="si"><b>'+slotName(s)+'</b><br>'+(i?esc(i.name)+'・第'+(i.gen||1)+'代・第'+i.day+'日<br><small>'+new Date(i.t).toLocaleString()+'</small>':'（空）')+'</div>'+(mode==='save'?'<button class="pri" data-sv="'+s+'">存入</button>':(i?'<button class="pri" data-ld="'+s+'">讀取</button>':''))+'</div>';});
 return h+'<p class="note">每日清晨自動存檔。存檔保存在此瀏覽器。結局冊跨存檔保留。</p>';};
MenuUI.log=function(){if(!S)return '';return S.back.slice(-100).reverse().map(function(b){return '<div class="logl'+(b.sp==='p'?' me':'')+'">'+(b.sp?'<b>'+esc(b.sp==='p'?pc().n:cn(b.sp))+'</b>':'')+esc(b.t)+'</div>';}).join('')||'<p class="note">尚無紀錄。</p>';};
MenuUI.full=function(){if(!S)return '';return '<p class="note">完整日誌（M20）：保存最近 '+S.full.length+' 幕全文。</p>'+S.full.slice(-60).reverse().map(function(f){return '<div class="logl"><b>第'+f.d+'日・'+PER_S[f.per]+'・'+esc((PLACES[f.pl]||{n:''}).n)+'</b><div style="white-space:pre-wrap">'+esc(f.t)+'</div></div>';}).join('')+'<h4>生平紀事</h4>'+S.log.slice(-60).reverse().map(function(l){return '<div class="logl">'+esc(l.t)+'</div>';}).join('');};
MenuUI.settings=function(){var P0=PRESETS[SET.preset]||PRESETS.custom;
 return '<h4>AI 說書人</h4><label class="field">AI 模式'+seg('ai',[[false,'離線劇情'],[true,'AI 生成']])+'</label>'
  +'<label class="field">來源'+seg('aiSrc',[['api','API 直連'],['manual','手動貼上（Grok App 等）']])+'</label>'
  +'<label class="field">服務商<select id="sPreset">'+PRESET_ORDER.map(function(k){return '<option value="'+k+'"'+(k===SET.preset?' selected':'')+'>'+PRESETS[k].n+'</option>';}).join('')+'</select></label><p class="note">'+esc(P0.key)+'</p>'
  +'<label class="field">Base URL<input id="sBase" value="'+esc(SET.base)+'" autocapitalize="off" autocorrect="off" spellcheck="false"></label>'
  +(SET.preset==='deepseek'?'<label class="field">模型'+seg('model',[['deepseek-chat','deepseek-chat（快）'],['deepseek-reasoner','deepseek-reasoner（強・較慢）']])+'</label><p class="note">reasoner 較慢、較費額度，適合複雜醫案與長劇情；日常用 chat 即可。</p>':'<label class="field">模型<input id="sModel" list="mdl" value="'+esc(SET.model)+'" autocapitalize="off" autocorrect="off" spellcheck="false"><datalist id="mdl">'+(MenuUI.models||P0.models||[]).map(function(m){return '<option value="'+esc(m)+'">';}).join('')+'</datalist></label>')
  +'<label class="field">API Key（只存在本機）<input id="sKey" type="password" value="'+esc(SET.key)+'" autocapitalize="off" autocorrect="off" spellcheck="false"></label>'
  +'<label class="field">額外標頭（選填，Header: 值）<input id="sHdr" value="'+esc(SET.hdr)+'" autocapitalize="off" spellcheck="false"></label>'
  +'<div class="row"><button class="btn pri" id="sSave">儲存</button><button class="btn" id="sTest">測試連線</button><button class="btn" id="sList">列出模型</button></div><div id="sMsg" class="note"></div>'
  +(AI.isBlocked()||(S&&S.aiPaused)?'<p class="note" style="color:#b8323a">AI 目前暫停：'+esc(AI.lastErr||(SET.aiBlock.split('\u0001')[1]||''))+' <button class="btn" id="sUnblock">恢復 AI</button></p>':'')
  +'<label class="field">溫度'+seg('temp',[[0.6,'穩'],[0.85,'中'],[1.05,'奔放']])+'</label><label class="field">逾時'+seg('aiTimeout',[[30,'30 秒'],[60,'60 秒'],[120,'120 秒']])+'</label>'
  +'<label class="field">AI 結局（M 結局冊）'+seg('aiEnd',[[true,'AI 書寫'],[false,'離線模板']])+'</label>'
  +'<h4>閱讀</h4><label class="field">打字機效果'+seg('typer',[[true,'開'],[false,'關']])+'</label><label class="field">文字速度'+seg('speed',[[1,'慢'],[2,'中'],[3,'快']])+'</label><label class="field">字級'+seg('font',[[15,'小'],[17,'中'],[19,'大']])+'</label>'
  +'<h4>遊戲</h4><label class="field">難度'+seg('diff',[['easy','爽玩'],['normal','一般'],['hard','困難']])+'</label><label class="field">自動用膳'+seg('autoEat',[[true,'開'],[false,'關']])+'</label>'
  +'<label class="field">劇情節奏（M18）'+seg('pace',[['slow','慢熱'],['mid','適中'],['fast','緊湊']])+'</label><label class="field">NPC 來訪頻率（M18）'+seg('visitf',[['low','少'],['mid','中'],['high','多']])+'</label>'
  +'<label class="field">世界大事密度（M26）'+seg('wdens',[['low','疏'],['mid','中'],['high','密']])+'</label><label class="field">世界節制（大事須有前因）'+seg('wsane',[[true,'開'],[false,'關']])+'</label>'
  +'<label class="field">知情防火牆（M13）'+seg('firewall',[[true,'開'],[false,'關']])+'</label><label class="field">秘密守秘（M22）'+seg('seald',[[true,'開'],[false,'關']])+'</label>'
  +'<label class="field">記憶深度（M21）'+seg('memd',[['mid','中'],['high','深']])+'</label><label class="field">AI 心態卡（M20）'+seg('bondd',[[true,'開'],[false,'關']])+'</label>'
  +'<label class="field">行動必有結果（M22）'+seg('actd',[[true,'開'],[false,'關']])+'</label><label class="field">NPC 命令必執行（M25）'+seg('ncmd',[[true,'開'],[false,'關']])+'</label>'
  +'<label class="field">宣告寬限（M27：情意上限 60、銀兩上限 100）'+seg('decld',[[true,'開'],[false,'關']])+'</label><label class="field">舊毒自動服藥'+seg('aflauto',[[true,'開'],[false,'關']])+'</label>'
  +'<p class="note">輸入框左邊按鈕切換：💬說（對白，只會被回應）→ ⚙指令（動作，或「某人命人…」導演命令，必定執行）→ 📜設定（作者宣告，必定成真）。句首可打 /說 /指令 /行動 /命令 /身份 /設定 /劇情，或用（括號）寫動作再接對白。</p>';};
Panels.bind=function(){$('shX').onclick=Sh.close;
 $('shTabs').addEventListener('click',function(e){var b=e.target.closest('button');if(!b)return;Sh.tab=b.getAttribute('data-tab');Sh.draw();});
 $('shB').addEventListener('click',function(e){var t=e.target.closest('button');if(!t)return;var a;
  if((a=t.getAttribute('data-act'))){if(a==='endLife'){Sh.close();UI.go('endLife');return;}var f=Panels.act[a];if(f)f(t.getAttribute('data-v'),t);return;}
  if((a=t.getAttribute('data-m'))){if(a==='alb'){Panels.album();return;}if(a==='title'){UI.dialog('回到標題','未存檔的進度會遺失（每日清晨有自動存檔）。',[['取消',null],['回到標題','pri',function(){Sh.close();UI.go('title');}]]);return;}Sh.tab=a;Sh.draw();return;}
  if((a=t.getAttribute('data-sv'))){saveSlot(a==='auto'?'auto':+a);Sh.draw();return;}
  if((a=t.getAttribute('data-ld'))){UI.loadGame(a==='auto'?'auto':+a);return;}
  if((a=t.getAttribute('data-set'))){var v=t.getAttribute('data-v');var dv=DEFSET[a];SET[a]=typeof dv==='boolean'?v==='true':(typeof dv==='number'?+v:v);saveSettings();applyLook();Sh.redraw();return;}
  if(t.id==='sSave'||t.id==='sTest'||t.id==='sList'){SET.base=$('sBase').value.trim();if($('sModel'))SET.model=$('sModel').value.trim();SET.key=$('sKey').value.trim();SET.hdr=$('sHdr').value.trim();saveSettings();
   if(t.id==='sSave'){toast('已儲存設定');return;}var m=$('sMsg');
   if(t.id==='sList'){m.textContent='讀取模型清單…';AI.listModels().then(function(L){MenuUI.models=L;Sh.redraw();var m2=$('sMsg');if(m2)m2.textContent=L.length?'✅ 找到 '+L.length+' 個模型：'+L.slice(0,12).join('、'):'（服務商沒有回傳模型清單）';},function(e){var m2=$('sMsg');if(m2)m2.textContent='❌ '+AI.errMsg(e);});return;}
   m.textContent='測試中…';AI.test().then(function(r){var m2=$('sMsg');if(m2)m2.textContent=(r.ok?'✅ ':'❌ ')+r.msg;});return;}
  if(t.id==='sUnblock'){AI.unblock();toast('AI 已恢復');Sh.redraw();return;}});
 $('shB').addEventListener('change',function(e){if(e.target.id==='sPreset'){var k=e.target.value;var P0=PRESETS[k];SET.preset=k;if(P0.base)SET.base=P0.base;if(P0.model)SET.model=P0.model;MenuUI.models=null;saveSettings();Sh.redraw();}if(e.target.id==='suBirth'){Panels.su.birth=e.target.value;Panels.act.suRoll();}});};
